ruuvi/com.ruuvi.station.ios

README.md
Some of this information is in the "will be available soon" category.
=> Add some description and links

station/Classes/Business/Services/Export/Temp/ExportServiceTemp.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/TagChartsScrollViewController.swift, station/Classes/Presentation/Presenters/Activity/RuuviLogo/ActivityPresenterRuuviLogo.swift
* charts reload without redraw
* if user zoomed in at the chart, he don’t be zoomed out on update
* move Realm to Background Queue
* added minimal showing time in ActivityPresenter
* showing indicator while chart datasource fetching
=> Chart optimizations

station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/SingleChart/View/ChartView/TagChartView.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/SingleChart/View/TagChartViewOutput.swift
* optimized the dynamic downsampling algorithms 
* correction visible range of xAxis values on scale or transition
=> Optimization for chart

Podfile, Podfile.lock, station.xcodeproj/project.pbxproj, station/Classes/Business/Charts/Operations/ChartFilterOperation.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/SingleChart/View/ChartView/TagChartView.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/SingleChart/View/TagChartViewInput.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/TagChartsViewModel.swift, station/Enums/MeasurementType.swift, station/Extensions/UIWindow+Shake.swift
* move filtering by dates to operation
* added Flex support by shake
* move reloadChart, fitZoomTo and chartData to viewModel with fetching by chartType
=> RU-265 main freeze when open chart

station/Classes/Business/Services/RuuviTag/Impl/RuuviTagServiceImpl.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/SingleChart/View/ChartView/TagChartView.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/SingleChart/View/TagChartViewInput.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/TagChartsViewModel.swift
* fixed switch to next tag if deleting tag 
* fixed loader hidding if deleting or adding tag
=> Fix for adding or deleting tag

Podfile, Podfile.lock, station.xcodeproj/project.pbxproj, station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/TagCharts.storyboard, station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/SingleChart/View/ProgressBar/ProgressBarView.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/TagChartsScrollViewController.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/TrippleChartView.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/TagChartsViewModel.swift
* updated charts and realm pods
* added progressBar to into charts
* moved FLEX into dev
=> Progress bar on initial chart loading

.swiftlint.yml, station/Classes/Core/LocalNotifications/Impl/LocalNotificationsManagerImpl.swift, station/Classes/Persistence/RuuviTag/Realm/RuuviTagPersistenceRealm.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Assembly/Scroll/CardsScrollConfigurator.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/CardsScrollViewController.swift, station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsPresenter.swift, station/Classes/Reactor/RuuviTag/Impl/RuuviTagReactorImpl.swift, station/Classes/Reactor/RuuviTag/RuuviTagReactor.swift
- resolved some swiftlint warnings
=> IOS-325 added check for nil measurement value

station/Classes/Business/Migration/toSQLite/MigrationManagerToSQLite.swift, station/Classes/Model/Ontology/Sensor/RuuviTag/RuuviTagSensor.swift, station/Classes/Persistence/RuuviTag/SQLite/RuuviTagPersistenceSQLite.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/CardsViewModel.swift, station/Classes/Tank/RuuviTag/Coordinator/RuuviTagTankCoordinator.swift
IOS-332 - app don't show last record after update
IOS-333 - don't migrate to sqlite for tags without a mac
=> 0.6(26) public beta issues resolve

station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Chart/View/ChartView/TagChartView.swift, station/Classes/Util/DateValueFormatter.swift
- return drawCircles representation for one point
- set min y axis length
=> IOS-338 min y axis length

station.xcodeproj/project.pbxproj, station/Classes/Presentation/Modules/Menu/Menu.storyboard
- also resolved pod install trouble
=> IOS-365 changed menu table background color

station/Classes/Core/MeasurementsService/Impl/MeasurementsServiceImpl.swift, station/Classes/Persistence/Alert/UserDefaults/AlertPersistenceUserDefaults.swift
=> IOS-379 added spacing between value and unit

station.xcodeproj/project.pbxproj, station/Classes/Business/Services/Alert/Impl/AlertServiceImpl+Process.swift, station/Classes/Business/Services/Export/Trunk/ExportServiceTrunk.swift, station/Classes/Model/Ontology/Measurement/Measurement.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Settings/Module/Assembly/Table/SettingsTableConfigurator.swift, station/Classes/Presentation/Modules/Settings/Module/Presenter/SettingsPresenter.swift, station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, station/Enums/AlertType.swift, station/Resources/Strings/en.lproj/Localizable.strings
- Alert notification is missing a title in English strings
- Tag Card bell icon does not blink when alert triggered after switching to Dew Point
- disable humidity alert on change unit to dew point
- IOS-383 export csv typo
=> Fixes for dew point alerts

station/Classes/Business/Services/Export/Trunk/ExportServiceTrunk.swift, station/Classes/Persistence/Assembly/PersistenceAssembly.swift, station/Classes/Persistence/WebTag/Realm/WebTagPersistenceRealm.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/CardsViewModel.swift, station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, station/Classes/Presentation/Modules/TagSettings/View/Table/TagSettingsTableViewController.swift, station/Classes/Presentation/Modules/TagSettings/View/TagSettingsViewModel.swift, station/Classes/Trunk/RuuviTag/Coordinator/RuuviTagTrunkCoordinator.swift
IOS-406 - universal links for verify authentication
IOS-407 - Add the sync status alert
IOS-409 - Export CSV translation for "Date" is missing
IOS-410 - 0.7(18) Synced network tag appears between physical and virtual tag
IOS-411 - 0.7(18) Saw claim buttons once never again
=> UserAPI bugfixes

Podfile, Podfile.lock, station.xcodeproj/project.pbxproj, station/Classes/Business/Services/Export/Trunk/ExportServiceTrunk.swift, station/Classes/Core/Assembly/CoreAssembly.swift, station/Classes/Core/MeasurementsService/Impl/MeasurementsServiceImpl.swift, station/Classes/Core/MeasurementsService/MeasurementsService.swift, station/Classes/Model/Ontology/Measurement/Measurement.swift, station/Enums/Language.swift, station/Extensions/String+Characters.swift, stationTests/MockAlertPersistence.swift, stationTests/MockCalibrationService.swift, stationTests/MockRuuviTag.swift, stationTests/Services/Alert/AlertServiceSpec.swift, stationTests/Services/MeasurementsService/MeasurementsServiceEnSpec.swift, stationTests/Services/MeasurementsService/MeasurementsServiceFiSpec.swift, stationTests/Services/MeasurementsService/MeasurementsServiceRuSpec.swift, stationTests/Services/MeasurementsService/MeasurementsServiceSvSpec.swift
resolve
- [Issue #163](https://github.com/ruuvi/com.ruuvi.station.ios/issues/163)
- [Issue #134](https://github.com/ruuvi/com.ruuvi.station.ios/issues/134)
=> IOS-417 decimal separator based on system locale

station/Classes/Core/MeasurementsService/Impl/MeasurementsServiceImpl.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/CardsScrollViewController.swift, station/Classes/Presentation/Modules/Dashboard/Chart/Assembly/TagChartAssembler.swift, station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartModuleInput.swift, station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Chart/View/ChartView/TagChartView.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsInteractor.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsInteractorInput.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/TagChartsScrollViewController.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/TagChartsViewOutput.swift, station/Classes/Util/DateValueFormatter.swift, stationTests/Services/MeasurementsService/MeasurementsServiceEnSpec.swift, stationTests/Services/MeasurementsService/MeasurementsServiceFiSpec.swift, stationTests/Services/MeasurementsService/MeasurementsServiceRuSpec.swift, stationTests/Services/MeasurementsService/MeasurementsServiceSvSpec.swift
- setup minimum fraction digits to 2
- updated tests for measurements service
=> Always show 2 decimals

station/Classes/Presentation/Modules/TagSettings/TagSettings.storyboard
=> #211 - added min distance for the range seek sliders

Podfile, Podfile.lock, station.xcodeproj/project.pbxproj
PR to Charts library: https://github.com/danielgindi/Charts/pull/4588
=> #220 Point pods to fixed Charts implementation

Podfile, Podfile.lock, station.xcodeproj/project.pbxproj
in order to fix isConnected crash
=> bump BTKit version

station.xcodeproj/project.pbxproj, station/Classes/Business/Assembly/BusinessAssembly.swift, station/Classes/Business/Migration/toPrune240/MigrationManagerToPrune240.swift, station/Classes/Persistence/RuuviTag/Realm/RuuviTagPersistenceRealm.swift, station/Classes/Persistence/RuuviTag/RuuviTagPersistence.swift, station/Classes/Persistence/RuuviTag/SQLite/RuuviTagPersistenceSQLite.swift, station/Classes/Persistence/Settings/UserDefaults/SettingsUserDefaults.swift, station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartModuleInput.swift, station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Assembly/Scroll/TagChartsScrollConfigurator.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsInteractor.swift, station/Classes/Presentation/Modules/Main/Assembly/MainInitializer.swift, station/Classes/Trunk/RuuviTag/Coordinator/RuuviTagTrunkCoordinator.swift, station/Classes/Trunk/RuuviTag/RuuviTagTrunk.swift
1. set pruning interval to 240h
2. remove entries from chart online (but not for downsampled case)
=> #206 Unify stored data history length with Android

station/Resources/Strings/en.lproj/InfoPlist.strings
hey there, huge fan of the sensors and app :)
just a small fix to a few typos i saw - feel free to merge if helpful :)
=> localization: fix some english permission typos

station/Classes/Presentation/Modules/Menu/Menu.storyboard, station/Classes/Presentation/Modules/Menu/View/Table/MenuTableEmbededViewController.swift
=> 200 added beta badge for sign in

station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartModuleOutput.swift, station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Chart/View/ChartView/TagChartView.swift, station/Classes/Presentation/Modules/Dashboard/Chart/View/TagChartViewOutput.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsInteractor.swift
https://user-images.githubusercontent.com/722716/117782459-16401a80-b25b-11eb-93ee-bf6d5ac2ddb8.MP4
=> Sync Charts Scale and Translate (see video)

station/Classes/Business/Services/Alert/Impl/AlertServiceImpl+Process.swift, station/Classes/Business/Services/Export/Trunk/ExportServiceTrunk.swift, station/Classes/Core/MeasurementsService/Impl/MeasurementsServiceImpl.swift, station/Classes/Core/MeasurementsService/MeasurementsService.swift, station/Classes/Model/Ontology/Measurement/Measurement.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/CardsViewModel.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/CardsScrollViewController.swift, station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartPresenter.swift
fix humidity calibration issue
correct humidity value in alertService
=> Fix Sensor offset calibration #215

station.xcodeproj/project.pbxproj, station/Classes/Business/Services/Sensor/Impl/SensorServiceImpl.swift, station/Classes/Business/Services/Sensor/SensorService.swift, station/Classes/Business/Services/UserProperties/Impl/UserPropertiesServiceImpl.swift, station/Classes/Core/Info/Impl/InfoProviderImpl.swift, station/Classes/Core/Permissions/Impl/PermissionsManagerImpl.swift, station/Classes/Core/Permissions/PermissionsManager.swift, station/Classes/Networking/Ruuvi/UserApi/RuuviNetworkUserApi.swift, station/Classes/Presentation/Modules/Share/Presenter/SharePresenter.swift, station/Classes/Presentation/Modules/TagsManager/Presenter/TagsManagerPresenter.swift
Deliverable: macOS target compiles
=> Approach to SPM

Packages/RuuviCloud/Sources/RuuviCloud/RuuviCloud.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/RuuviCloudApi.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Request/RuuviCloudApiGetSettingsRequest.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Request/RuuviCloudApiPostSettingRequest.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Response/RuuviCloudApiGetSettingsResponse.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Response/RuuviCloudApiPostSettingResponse.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Settings/RuuviCloudApiSettings.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/RuuviCloudApiURLSession.swift, Packages/RuuviCloud/Sources/RuuviCloudPure/RuuviCloudPure.swift, Packages/RuuviOntology/Sources/RuuviOntology/Common/RuuviCloudSettings.swift, Packages/RuuviService/RuuviService.podspec, Packages/RuuviService/Sources/RuuviService/RuuviServiceAppSettings.swift, Packages/RuuviService/Sources/RuuviService/RuuviServiceCloudSync.swift, Packages/RuuviService/Sources/RuuviService/RuuviServiceFactory.swift, Packages/RuuviService/Sources/RuuviServiceAppSettings/RuuviServiceAppSettingsImpl.swift, Packages/RuuviService/Sources/RuuviServiceCloudSync/RuuviServiceCloudSyncImpl.swift, Podfile, Podfile.lock, station/Classes/Business/Assembly/BusinessAssembly.swift, station/Classes/Presentation/Modules/Settings/Module/Assembly/Table/SettingsTableConfigurator.swift, station/Classes/Presentation/Modules/Settings/Module/Presenter/SettingsPresenter.swift
Temperature/Humidity/Pressure units
=> Save Units in Cloud

fastlane/Appfile, fastlane/Fastfile
Ruuvi Cloud under feature toggle
=> TestFlight continuous delivery

fastlane/Fastfile
=> Beta Candidate 18

station/Classes/Presentation/Modules/Menu/Menu.storyboard, station/Classes/Presentation/Modules/Menu/Presenter/MenuPresenter.swift, station/Classes/Presentation/Modules/Menu/View/Table/MenuTableEmbededViewController.swift, station/Classes/Presentation/Modules/Menu/View/Table/MenuTableViewController.swift, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings, station/Resources/Strings/sv.lproj/Localizable.strings
=> Fix localisations 

README.md
Build is similar to 0.7(94) BC28
=> Renew Distribution Certificate

Packages/RuuviService/Sources/RuuviServiceAlert/AlertPersistence/UserDefaults/AlertPersistenceUserDefaults.swift, station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, station/Classes/Presentation/Modules/TagSettings/View/Table/TagSettingsTableViewController.swift, station/Classes/Presentation/Modules/TagSettings/View/TagSettingsViewModel.swift
basically now you CAN set alerts without connected state
=> new Alerts availability UX

Podfile.lock, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift
Fixed bug with charts showed for other sensor
=> Submit Candidate 5

Packages/RuuviService/Sources/RuuviServiceOffsetCalibration/RuuviServiceAppOffsetCalibrationImpl.swift, Packages/RuuviService/Sources/RuuviServiceSensorProperties/RuuviServiceSensorPropertiesImpl.swift
allow set image and name of shared sensor
=> Submit Candidate 6

station/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/Presenter/OffsetCorrectionPresenter.swift
Fix first opening of migrated sensor settings
=> Submit Candidate 9

station/Classes/Presentation/Modules/TagSettings/TagSettings.storyboard
Fixed "Back" button text on offset and updated localisations
=> Submit Candidate 10

station/Classes/Application/Features/FeatureToggle.swift, station/Classes/Presentation/FLEX/FLEXFeatureTogglesViewController.swift, station/Classes/Presentation/Modules/Dashboard/Chart/View/ChartView/TagChartView.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsInteractor.swift, station/Resources/JSONs/FeatureToggles.json
=> #198 fix synced zooming by setting fixed width 

Packages/RuuviCloud/Sources/RuuviCloud/RuuviCloud.swift, Packages/RuuviMigration/Sources/RuuviMigrationImpl/fixRHAlerts/RuuviMigrationFixRHAlerts.swift, Podfile, Podfile.lock, iOS.xcodeproj/project.pbxproj, macOS.xcodeproj/project.pbxproj, station.xcodeproj/project.pbxproj, station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Chart/View/ChartView/DateValueFormatter.swift, station/Classes/Presentation/Modules/Dashboard/Chart/View/ChartView/TagChartView.swift
the grid is fixed, left and right labels are shown, right axis is shown
=> New UX for Charts

station.xcodeproj/project.pbxproj, station/station.entitlements
=> Add support for Universal Link

station.xcodeproj/project.pbxproj
Adds the new constant files to the dev target.
=> Remove SwinjectPropertyLoader bug fix

station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/Owner.storyboard, station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/View/OwnerViewController.swift
=> Make verify ownership popup scrollable

fastlane/Fastfile
if not add error message to release notes.
=> Check if pr title & body exist

fastlane/Fastfile
=> Merge dev to alpha (up to #636)

fastlane/Fastfile
=> Merge dev (fix fastfile)

station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/Owner.storyboard
Change truncation mode and spacing between label and button in owner view.
=> Merge ui fix from dev

station.xcodeproj/project.pbxproj, station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/Owner.storyboard
- Re-do the UI from scratch to introduce `UIScrollView`
- Add correct constraints -> view can be scrolled if localized text is too long
=> In claim sensor pop-up verify ownership button not visible on iPhone SE. #602

Packages/RuuviDaemon/Sources/RuuviDaemonCloudSync/RuuviDaemonCloudSyncWorker.swift, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings
=> Sync everything from Daemon

Packages/RuuviDaemon/Sources/RuuviDaemonCloudSync/RuuviDaemonCloudSyncWorker.swift, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings
* sync all in daemon
* update localizations
=> Sync everything from Daemon (#658)

station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/CardsScrollViewController.swift
=> fix: Add items count check before scrolling left and right #642

station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift
feature: Organise sensors alphabetically #583
=> feature: Organise sensors alphabetically  #583

station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/View/CardView.xib
Fix #662  and another bug related to #583
=> Fix: Sensor name is not showing fully

Packages/RuuviService/Sources/RuuviServiceAuth/RuuviServiceAuthImpl.swift, Packages/RuuviService/Sources/RuuviServiceFactory/RuuviServiceFactory.swift, station/Classes/Application/AppAssembly.swift
=> fix: Make lastSyncDate nil when user log out #644

Packages/RuuviService/Sources/RuuviServiceAuth/RuuviServiceAuthImpl.swift, Packages/RuuviService/Sources/RuuviServiceFactory/RuuviServiceFactory.swift, Packages/RuuviService/Sources/RuuviServiceMeasurement/RuuviServiceMeasurementImpl.swift, station/Classes/Application/AppAssembly.swift
=> Fix: On second device cloud sensor charts are only showing 2 days

station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, station/Classes/Presentation/Modules/TagSettings/TagSettings.storyboard, station/Classes/Presentation/Modules/TagSettings/View/Table/TagSettingsTableViewController.swift, station/Classes/Presentation/Modules/TagSettings/View/TagSettingsViewModel.swift
This section should be visible to the owners only.
=> Fix: Hide offset correction for the user who is not the owner of the sensor #670

station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, station/Classes/Presentation/Modules/TagSettings/View/Table/TagSettingsTableViewController.swift, station/Classes/Presentation/Modules/TagSettings/View/TagSettingsViewModel.swift
Resetting settings as soon as a sensor is removed.
=> Fix: Clear previous settings when a sensor is removed #595

station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartModuleInput.swift, station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsInteractor.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/Presenter/OffsetCorrectionPresenter.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/View/OffsetCorrectionViewModel.swift
This rectification solves the issues #468 #547  #585
=> Fix: Make offset correction affect only UI layer

Packages/RuuviService/Sources/RuuviServiceCloudSync/RuuviServiceCloudSyncImpl.swift
This solve the issue where the cloud sensors may not sync with the device.
=> Fix: Rectify syncSensors method to sync cloud data #596

Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Advertisement/RuuviTagAdvertisementDaemonBTKit.swift, Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Heartbeat/RuuviTagHeartbeatDaemonBTKit.swift, Packages/RuuviPersistence/Sources/RuuviPersistenceSQLite/RuuviPersistenceSQLite.swift, Packages/RuuviRepository/Sources/RuuviRepositoryCoordinator/RuuviRepositoryCoordinator.swift, station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartPresenter.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/Presenter/OffsetCorrectionPresenter.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/View/OffsetCorrectionViewModel.swift, station/Extensions/Double+Temperature.swift
Breaking changes
These commits fix issue #468 #547. However, quite a number of changes made in several places that could potentially affect other things. 
Also, a slight refactor is required, especially the removal of a few unused codes once the build pass QA.
=> Fix: Make offset correction affect UI layer only

Packages/RuuviService/Sources/RuuviService/RuuviServiceExport.swift, Packages/RuuviService/Sources/RuuviServiceExport/RuuviServiceExportImpl.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsInteractor.swift, station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift
This is related to issue #468 #547
=> fix: Make export CSV file contains the offset corrected data

station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsInteractor.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsInteractorInput.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/TagChartsScrollViewController.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/TagChartsViewInput.swift
Multiple sensors can be synced concurrently
Refactor code snippet related to issue #657
=> fix: Enable concurrent sensors syncing from GATT #643

Packages/RuuviCloud/Sources/RuuviCloud/RuuviCloudApiError.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Response/RuuviCloudApiBaseResponse.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Response/RuuviCloudApiClaimResponse.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Response/RuuviCloudApiUserResponse.swift, Packages/RuuviContext/Sources/RuuviContextSQLite/SQLiteContextGRDB.swift, Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Properties/RuuviTagPropertiesDaemonBTKit.swift, Packages/RuuviNotification/Sources/RuuviNotificationLocal/RuuviNotificationLocalImpl.swift, Packages/RuuviOntology/Sources/RuuviOntology/Mappers/RuuviTag+RuuviTagSensor.swift, Packages/RuuviOntology/Sources/RuuviOntology/Sensor/CloudSensor.swift, Packages/RuuviOntology/Sources/RuuviOntology/Sensor/RuuviTag/RuuviTagSensor.swift, Packages/RuuviOntology/Sources/RuuviOntology/Sensor/Sensor.swift, Packages/RuuviOntology/Sources/RuuviOntologyRealm/RuuviTagRealm+RuuviTagSensor.swift, Packages/RuuviOntology/Sources/RuuviOntologySQLite/RuuviTagSQLite.swift, Packages/RuuviPersistence/Sources/RuuviPersistenceRealm/RuuviPersistenceRealm.swift, Packages/RuuviPersistence/Sources/RuuviPersistenceSQLite/RuuviPersistenceSQLite.swift, Packages/RuuviService/Sources/RuuviServiceCloudSync/RuuviServiceCloudSyncImpl.swift, station.xcodeproj/project.pbxproj, station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/Assembly/OwnerConfigurator.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/Presenter/OwnerPresenter.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/View/OwnerViewController.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/View/OwnerViewInput.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/View/OwnerViewOutput.swift, station/Extensions/Errors/RuuviCloudApiError+LocalizedError.swift, station/Extensions/String+Email.swift, station/Resources/Strings/en.lproj/Localizable.strings
Fix: #604 
Contains breaking changes! Requires careful checking before merging.
=> Fix: Show error for already claimed sensor #604

Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Response/RuuviCloudApiUserResponse.swift, Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Advertisement/RuuviTagAdvertisementDaemonBTKit.swift, Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Heartbeat/RuuviTagHeartbeatDaemonBTKit.swift, Packages/RuuviOntology/Sources/RuuviOntology/Measurement/RuuviMeasurement.swift, Packages/RuuviOntology/Sources/RuuviOntology/Sensor/CloudSensor.swift, Packages/RuuviPersistence/Sources/RuuviPersistenceSQLite/RuuviPersistenceSQLite.swift, Packages/RuuviRepository/Sources/RuuviRepositoryCoordinator/RuuviRepositoryCoordinator.swift, Packages/RuuviService/Sources/RuuviServiceFactory/RuuviServiceFactory.swift, station/Classes/Application/AppAssembly.swift, station/Classes/Application/AppAssemblyConstants.swift, station/Classes/Presentation/Assembly/PresentationConstants.swift, station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartModuleInput.swift, station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsInteractor.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/TagChartsScrollViewController.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/Presenter/OffsetCorrectionPresenter.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/View/OffsetCorrectionViewModel.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/Presenter/OwnerPresenter.swift, station/Classes/Presentation/Modules/TagSettings/View/Table/TagSettingsTableViewController.swift, station/Classes/Presentation/Modules/TagSettings/View/TagSettingsViewModel.swift, station/Extensions/Double+Temperature.swift
Remove unnecessary codes and blank spaces, and comply with swiftlint.
=> refactor: Follow swiftlint convensions

station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Router/CardsRouter.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Router/CardsRouterInput.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/CardsViewOutput.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/CardsScrollViewController.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/View/CardView.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/View/CardView.xib, station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Router/TagChartsRouter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Router/TagChartsRouterInput.swift, station/Classes/Presentation/Modules/Dashboard/Charts/TagCharts.storyboard, station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/TagChartsScrollViewController.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/TagChartsViewOutput.swift, station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsModuleInput.swift, station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, station/Classes/Presentation/Modules/TagSettings/View/Table/TagSettingsTableViewController.swift, station/Classes/Presentation/Modules/TagSettings/View/TagSettingsViewInput.swift, station/Classes/Presentation/Modules/WebTagSettings/Presenter/WebTagSettingsModuleInput.swift, station/Classes/Presentation/Modules/WebTagSettings/Presenter/WebTagSettingsPresenter.swift, station/Classes/Presentation/Modules/WebTagSettings/View/Table/WebTagSettingsTableViewController.swift, station/Classes/Presentation/Modules/WebTagSettings/View/WebTagSettingsViewInput.swift
Breaking changes!
This is a fat commit as the settings affect several files.
=> feature: Make alert bell tap open alert settings #610

Packages/RuuviAnalytics/RuuviAnalytics.podspec, Packages/RuuviAnalytics/Sources/RuuviAnalyticsImpl/RuuviAnalyticsImpl.swift, Packages/RuuviStorage/Sources/RuuviStorage/RuuviStorage.swift, Packages/RuuviStorage/Sources/RuuviStorageCoordinator/RuuviStorageCoordinator.swift, Podfile.lock, station/Classes/Application/AppAssembly.swift
=> feature: Add analytics events

Packages/RuuviAnalytics/Sources/RuuviAnalyticsImpl/RuuviAnalyticsImpl.swift, station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, station/Classes/Presentation/Modules/TagSettings/TagSettings.storyboard, station/Classes/Presentation/Modules/TagSettings/View/Table/TagSettingsTableViewController.swift, station/Classes/Presentation/Modules/TagSettings/View/TagSettingsViewInput.swift, station/Classes/Presentation/Modules/TagSettings/View/TagSettingsViewOutput.swift
=> feature: Remove UUID from tag settings screen

Modules/RuuviLocationPicker/Sources/RuuviLocationPicker/Resources/LocationPicker.storyboard, Modules/RuuviOnboard/Sources/RuuviOnboard/Pages/RuuviOnboardImageTitleViewController.swift, Modules/RuuviOnboard/Sources/RuuviOnboard/Pages/RuuviOnboardPagesViewController.swift, Modules/RuuviOnboard/Sources/RuuviOnboard/Pages/RuuviOnboardStartViewController.swift, station/Classes/Presentation/Assembly/PresentationAssembly.swift
=> Style: Fix style mismatch with Android app

Packages/RuuviService/Sources/RuuviServiceExport/RuuviServiceExportImpl.swift, station/Extensions/Structs/ExportHeadersProvider.swift
=> feature: Update file name format and add RSSI column #253

Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift, station/Classes/Presentation/Modules/Dashboard/Chart/View/ChartView/TagChartView.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/TagChartsScrollViewController.swift
Breaking changes!
Advertisement and heartbeats both saves to local storage.
Chart left padding is increased
Chart x-Axis label count unified to Android app
=> fix: Save heartbeats and advertisement #744 #661 #591

Packages/RuuviService/Sources/RuuviService/RuuviServiceExport.swift, Packages/RuuviService/Sources/RuuviServiceExport/RuuviServiceExportImpl.swift, station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift
=> fix: Make sensor settings optional for CSV export #253

station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/CardsScrollViewController.swift, station/Classes/Presentation/Modules/Menu/Menu.storyboard, station/Classes/Presentation/Modules/Menu/View/Table/MenuTableEmbededViewController.swift
This PR contains:
1. Fix of issue #535 
2. Remove Beta label from menu
=> Remove gesture to open chart 

station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/CardsViewInput.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/CardsViewOutput.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/CardsScrollViewController.swift, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings, station/Resources/Strings/sv.lproj/Localizable.strings
Add keep connection popup when tag settings screen is opened for the first time.
=> feature: Add keep connection popup #492

station/Classes/Presentation/Modules/Dashboard/Chart/View/ChartView/TagChartView.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsInteractor.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/TagChartsScrollViewController.swift, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings, station/Resources/Strings/sv.lproj/Localizable.strings
Breaking changes!
Chart not visible for missing sensors
Fix the issue where GATT sync was showing the missing sensors on the chart
=> fix: Make chart respect the missing sensor #751 #763

station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsInteractor.swift
This is a supplementary commit of PR #765 
Contains issue #763 #751
=> feature: Respect missing sensor on chart #763 #751

station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, station/Classes/Presentation/Modules/TagSettings/View/Table/TagSettingsTableViewController.swift, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings
=> feature: Show version for tags with older fw e.g. <= 2.5.9

station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, station/Classes/Presentation/Modules/TagSettings/View/Table/TagSettingsTableViewController.swift, station/Classes/Presentation/Modules/TagSettings/View/TagSettingsViewModel.swift, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings, station/Resources/Strings/sv.lproj/Localizable.strings
=> feature: Hide offset correction for missing sensors #751

station/Classes/Application/UniversalLinks/Coordinator/Impl/UniversalLinkCoordinatormpl.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Assembly/Scroll/CardsScrollConfigurator.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/CardsViewInput.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/CardsScrollViewController.swift, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings, station/Resources/Strings/sv.lproj/Localizable.strings
=> feature: Add alert for already logged in user #653

Packages/RuuviService/Sources/RuuviServiceExport/RuuviServiceExportImpl.swift
=> fix: Hide missing sensor values from exported csv #751

Packages/RuuviPersistence/Sources/RuuviPersistence/RuuviPersistence.swift, Packages/RuuviPersistence/Sources/RuuviPersistenceRealm/RuuviPersistenceRealm.swift, Packages/RuuviPersistence/Sources/RuuviPersistenceSQLite/RuuviPersistenceSQLite.swift, Packages/RuuviService/Sources/RuuviServiceExport/RuuviServiceExportImpl.swift, Packages/RuuviStorage/Sources/RuuviStorage/RuuviStorage.swift, Packages/RuuviStorage/Sources/RuuviStorageCoordinator/RuuviStorageCoordinator.swift, station/Classes/Application/AppAssembly.swift
=> fix: Make export contain 10days historical data #711

Packages/RuuviAnalytics/Sources/RuuviAnalyticsImpl/RuuviAnalyticsImpl.swift
Also fix an issue where added_tags and df3, df4, df5 tags were sending duplicated values from shared sensors.
Issue: #782
=> feature: Add metrics for DF2 tags #782

station/Resources/Plists/Info.plist
Add missing metrics for tags and fix known issues.
=> Minor improvements on firebase analytics

Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalSettings.swift, Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift, station.xcodeproj/project.pbxproj, station/Classes/Application/Features/FeatureToggle.swift, station/Classes/Presentation/FLEX/FLEXFeatureTogglesViewController.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Assembly/Scroll/CardsScrollConfigurator.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Router/CardsRouter.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Router/CardsRouterInput.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/CardsViewInput.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/CardsViewOutput.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/CardsScrollViewController.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/Assembly/OwnerConfigurator.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/Presenter/OwnerPresenter.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/Router/OwnerRouter.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/Router/OwnerRouterInput.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/View/OwnerViewController.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/View/OwnerViewInput.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/View/OwnerViewOutput.swift, station/Extensions/UINavigationController.swift, station/Resources/JSONs/FeatureToggles.json, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings, station/Resources/Strings/sv.lproj/Localizable.strings
=> feature: Show firmware update popups for tags < 5 data format

station/Classes/Presentation/Modules/SignIn/Presenter/SignInPresenter.swift
Fixes an issue where while cloud syncing if app enters background and comes back to foreground the loading spinner gets frozen.
=> fix: Make activity indicator spinning when enters foreground #749

station.xcodeproj/project.pbxproj, station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Chart/View/ChartView/TagChartView.swift, station/Classes/Presentation/Modules/Dashboard/Chart/View/TagChartViewInput.swift
=> fix: Make sensor show smooth chart #754

station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartPresenter.swift
=> fix: Remove curve from line chart #821

Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Advertisement/RuuviTagAdvertisementDaemonBTKit.swift, Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Heartbeat/RuuviTagHeartbeatDaemonBTKit.swift, station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsInteractor.swift
Data points are not dropped aggressively now.  However, the database size has to be monitored in this build.
#205
=> feature: Make chart update with each data point stored #205

Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Advertisement/RuuviTagAdvertisementDaemonBTKit.swift, Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Heartbeat/RuuviTagHeartbeatDaemonBTKit.swift, Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalSettings.swift, Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsInteractor.swift
Issue #205 
When the chart is foreground store all data points, otherwise respect the settings.
=> feature: Make charts update realtime when foreground #205

station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsInteractor.swift
=> feature: Synchronise charts only horizontally #750

Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalSettings.swift, Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsPresenter.swift
=> fix: Ask to enable bluetooth on chart sync, if disabled #531

station.xcodeproj/project.pbxproj, station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Chart/View/ChartView/CustomXAxisRenderer.swift, station/Classes/Presentation/Modules/Dashboard/Chart/View/ChartView/TagChartView.swift, station/Classes/Presentation/Modules/Dashboard/Chart/View/TagChartViewInput.swift
=> feature: Improve chart timeline #753

Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalSettings.swift, Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsPresenter.swift
=> fix: Make chart sync properly when bluetooth is available #833

station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Router/CardsRouter.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Router/CardsRouterInput.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Router/TagChartsRouter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Router/TagChartsRouterInput.swift, station/Classes/Presentation/Modules/Menu/Menu.storyboard, station/Classes/Presentation/Modules/Menu/Presenter/MenuModuleOutput.swift, station/Classes/Presentation/Modules/Menu/Presenter/MenuPresenter.swift, station/Classes/Presentation/Modules/Menu/View/MenuViewOutput.swift, station/Classes/Presentation/Modules/Menu/View/Table/MenuTableEmbededViewController.swift, station/Resources/Strings/de.lproj/Localizable.strings, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings, station/Resources/Strings/sv.lproj/Localizable.strings
=> feature: Add buy ruuvi gateway option on the menu #818

station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/CardsScrollViewController.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/View/CardView.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/View/CardView.xib
=> feature: Hide icon and values for missing sensors on card #814

station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/CardsScrollViewController.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/View/CardView.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/View/CardView.xib, station/Resources/Strings/de.lproj/Localizable.strings, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings, station/Resources/Strings/sv.lproj/Localizable.strings
=> feature: Add unit detail for movement #815

station/Classes/Application/Features/FeatureToggle.swift, station/Classes/Presentation/FLEX/FLEXFeatureTogglesViewController.swift, station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, station/Classes/Presentation/Modules/TagSettings/TagSettings.storyboard, station/Classes/Presentation/Modules/TagSettings/View/Table/TagSettingsTableViewController.swift, station/Classes/Presentation/Modules/TagSettings/View/TagSettingsViewModel.swift, station/Resources/JSONs/FeatureToggles.json
=> feature: Hide alert settings for missing sensors #819

Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalSettings.swift, Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/CardsViewModel.swift, station/Classes/Presentation/Modules/Settings/Submodules/Heartbeat/Heartbeat.storyboard, station/Classes/Presentation/Modules/Settings/Submodules/Heartbeat/Presenter/HeartbeatPresenter.swift, station/Classes/Presentation/Modules/Settings/Submodules/Heartbeat/View/HeartbeatViewModel.swift, station/Classes/Presentation/Modules/Settings/Submodules/Heartbeat/View/SwiftUI/HeartbeatList.swift, station/Classes/Presentation/Modules/Settings/Submodules/Heartbeat/View/Table/HeartbeatTableViewController.swift
=> feature: Remove RSSI settings #402

station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/Presenter/OwnerPresenter.swift
=> feature: Make claim page enable only for unclaimed tags #823

station/Classes/Presentation/Modules/TagSettings/Submodules/DFU/DFUModuleFactory.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/DFU/Presenter/DFUPresenter.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/DFU/View/DFUViewModel.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/DFU/View/SwiftUI/DFUUIView.swift, station/Resources/Strings/de.lproj/Localizable.strings, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings, station/Resources/Strings/sv.lproj/Localizable.strings
=> feature: Show warning if battery is low on firmware update attempt #836

Packages/RuuviService/Sources/RuuviService/GATTService.swift, Packages/RuuviService/Sources/RuuviServiceGATT/Operations/RuuviTagReadLogsOperation.swift, Packages/RuuviService/Sources/RuuviServiceGATT/Queue/GATTServiceQueue.swift, iOS.xcodeproj/project.pbxproj, macOS.xcodeproj/project.pbxproj, station.xcodeproj/project.pbxproj, station/Classes/Presentation/Modules/Dashboard/Charts/Assembly/Scroll/TagChartsScrollConfigurator.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsInteractor.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/TagChartsScrollViewController.swift, station/Classes/Presentation/Modules/TagSettings/Assembly/Table/TagSettingsTableConfigurator.swift, station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift
=> fix: Sync chart full when it's empty or synced for the first time #317

station/Resources/Strings/fr.lproj/Localizable.strings
=> Update localisation #815

Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSyncStateUserDefaults.swift
=> refactor: Remove assertion failure block #317

station/Classes/Presentation/Modules/Dashboard/Cards/Cards.storyboard, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/CardsViewInput.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/CardsViewOutput.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/CardsScrollViewController.swift, station/Resources/Strings/de.lproj/Localizable.strings, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings, station/Resources/Strings/sv.lproj/Localizable.strings
=> feature: Unify no sensors screen #485

Packages/RuuviOntology/Sources/RuuviOntology/Common/RuuviTagProtocol.swift, Packages/RuuviOntology/Sources/RuuviOntologyRealm/RuuviTagRealm+RuuviTagSensor.swift, Packages/RuuviOntology/Sources/RuuviOntologyRealm/RuuviTagRealm.swift, Packages/RuuviPersistence/Sources/RuuviPersistenceRealm/RuuviPersistenceRealm.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Cards.storyboard, station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, station/Classes/Presentation/Modules/TagSettings/TagSettings.storyboard, station/Classes/Presentation/Modules/TagSettings/View/Table/TagSettingsTableViewController.swift, station/Resources/Strings/de.lproj/Localizable.strings, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings, station/Resources/Strings/sv.lproj/Localizable.strings
- Refactor in realm persistence for tags without mac id.
=> feature: Use popup for sensor rename #820

station/Classes/Presentation/Modules/Settings/Module/Presenter/SettingsPresenter.swift, station/Classes/Presentation/Modules/Settings/Submodules/Language/Presenter/LanguagePresenter.swift, station/Classes/Presentation/Modules/Settings/Submodules/Language/View/LanguageViewInput.swift, station/Classes/Presentation/Modules/Settings/Submodules/Language/View/Table/LanguageTableViewController.swift, station/Classes/Presentation/Modules/Settings/Submodules/Selection/Model/SelectionItem.swift, station/Classes/Presentation/Modules/Settings/Submodules/Selection/View/Table/SelectionTableViewController.swift
=> feature: Show default checkmark for selected item #175

station.xcodeproj/project.pbxproj, station/Classes/Presentation/Modules/SignIn/Presenter/SignInPresenter.swift, station/Classes/Presentation/Modules/SignIn/SignIn.storyboard, station/Classes/Presentation/Modules/SignIn/View/SignInViewInput.swift, station/Classes/Presentation/Modules/SignIn/View/SignInViewModel.swift, station/Classes/Presentation/Modules/SignIn/View/SignInViewOutput.swift, station/Classes/Presentation/Modules/SignIn/View/ViewController/Helper/RuuviCodeTextField.swift, station/Classes/Presentation/Modules/SignIn/View/ViewController/Helper/RuuviCodeView.swift, station/Classes/Presentation/Modules/SignIn/View/ViewController/SignInViewController.swift, station/Resources/Strings/de.lproj/Localizable.strings, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings, station/Resources/Strings/sv.lproj/Localizable.strings
=> feature: Change code text field to code box #816

Packages/RuuviService/Sources/RuuviServiceAuth/RuuviServiceAuthImpl.swift, station/Classes/Presentation/Modules/SignIn/View/ViewController/Helper/RuuviCodeView.swift
- Fix bug on #816 
- Fix an issue where the menu was not closing after signing out
=> fix: Make pasting available for all boxes #816

Modules/RuuviOnboard/RuuviOnboard.podspec, Modules/RuuviOnboard/Sources/RuuviOnboard/Pages/Helpers.swift, Modules/RuuviOnboard/Sources/RuuviOnboard/Pages/RuuviOnboardCloudSigninViewController.swift, Modules/RuuviOnboard/Sources/RuuviOnboard/Pages/RuuviOnboardImageTitleViewController.swift, Modules/RuuviOnboard/Sources/RuuviOnboard/Pages/RuuviOnboardStartViewController.swift, Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalSettings.swift, Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/Background/RuuviLocalImagesUserDefaults.swift, Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift, Packages/RuuviPool/Sources/RuuviPoolCoordinator/RuuviPoolCoordinator.swift, Packages/RuuviVirtual/Sources/RuuviVirtualPersistence/VirtualPersistenceRealm.swift, Podfile.lock, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsInteractor.swift, station/Classes/Presentation/Modules/Settings/Module/Presenter/SettingsPresenter.swift, station/Extensions/Array+AnyRuuviTagSensor.swift
fix: Fix an issue where first card may not update #873
fix: Fix layout issue for iPhone SE Gen 1 #817
=> fix: First sensor card may not be updating

station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift
=> fix: Make first cloud sensor card update after launch #873

station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/CardsViewModel.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/CardsScrollViewController.swift
=> fix: Show humidity alert on below or above threshold #888

Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/Presenter/DiscoverPresenter.swift, Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/View/DiscoverViewInput.swift, Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/View/Table/DiscoverTableViewController.swift
=> fix: Make not added tags visible #898

Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/Presenter/DiscoverPresenter.swift, Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/View/DiscoverViewInput.swift, Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/View/Table/DiscoverTableViewController.swift
=> Fixed an issue where adding one tag making other undiscoverable

ruuvi-widgets/Model/WidgetEntry.swift, ruuvi-widgets/Provider/WidgetProvider.swift, station.xcodeproj/project.pbxproj, station/Resources/Plists/Info.plist
=> fix: Make widget preview screen show state based on user login status

station.xcodeproj/project.pbxproj, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Resources/Plists/Info.plist
=> fix: Fix an issue where updating the app from old version asking user to sign in

ruuvi-widgets/Provider/WidgetProvider.swift, ruuvi-widgets/RuuviWidgets.swift, ruuvi-widgets/View Model/WidgetViewModel.swift, ruuvi-widgets/View/EmptyWidgetView.swift, ruuvi-widgets/View/SimpleWidgetView.swift, ruuvi-widgets/View/UnauthorizedView.swift, station.xcodeproj/project.pbxproj, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Resources/Plists/Info.plist, station/Resources/Strings/de.lproj/Localizable.strings, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings, station/Resources/Strings/sv.lproj/Localizable.strings
=> Add localisation on Widget #493

Packages/RuuviLocal/RuuviLocal.podspec, Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalSyncState.swift, Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSyncStateUserDefaults.swift, Packages/RuuviService/Sources/RuuviServiceAuth/RuuviServiceAuthImpl.swift, Packages/RuuviService/Sources/RuuviServiceSensorRecords/RuuviServiceSensorRecordsImpl.swift, Podfile.lock, station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsInteractor.swift, station/Classes/Presentation/Modules/Menu/Presenter/MenuPresenter.swift, station/Classes/Presentation/Modules/Menu/View/MenuViewModel.swift, station/Classes/Presentation/Modules/Menu/View/MenuViewOutput.swift, station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift
=> fix: Make gatt sync fetch points from last sync time to now #927

Packages/RuuviLocation/Sources/RuuviLocationService/LocationPersistence/LocationAppleClass.swift, Packages/RuuviLocation/Sources/RuuviLocationService/RuuviLocationServiceApple.swift, Packages/RuuviOntology/Sources/RuuviOntology/Common/Location.swift, Packages/RuuviVirtual/Sources/RuuviVirtualModel/WebTagRealm.swift, station.xcodeproj/project.pbxproj, station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/CardsScrollViewController.swift
=> fix: Remove movements text from location, and show state #934

ruuvi-widgets/Enum/WidgetSensorEnum.swift, ruuvi-widgets/Helper/MeasurementService.swift, ruuvi-widgets/Provider/WidgetProvider.swift, ruuvi-widgets/View Model/WidgetViewModel.swift, ruuvi-widgets/View/SimpleWidgetView.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift
=> fix: Modify widget localisation more reliable #493

Modules/RuuviOnboard/Sources/RuuviOnboard/Resources/de.lproj/RuuviOnboard.strings
=> fix: Localisation key #942

station/Classes/Presentation/Modules/WebTagSettings/Presenter/WebTagSettingsPresenter.swift, station/Classes/Presentation/Modules/WebTagSettings/View/Table/WebTagSettingsTableViewController.swift, station/Classes/Presentation/Modules/WebTagSettings/WebTagSettings.storyboard
=> fix: Make changes in settings affect immediately #934

Packages/RuuviAnalytics/Package.swift, Packages/RuuviAnalytics/RuuviAnalytics.podspec, Packages/RuuviAnalytics/Sources/RuuviAnalyticsImpl/RuuviAnalyticsImpl.swift, Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalSettings.swift, Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift, Podfile.lock, station.xcworkspace/xcshareddata/xcschemes/station_dev.xcscheme, station/Classes/Application/AppAssembly.swift, station/Classes/Application/AppAssemblyConstants.swift, station/Classes/Application/AppState/Impl/AppStateServiceImpl.swift
=> fix: Unify analytics with android app #755 #904

station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift
=> fix: Make cloud mode toggle switch data source properly #920

Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Advertisement/RuuviTagAdvertisementDaemonBTKit.swift, Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Heartbeat/RuuviTagHeartbeatDaemonBTKit.swift, Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalSettings.swift, Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift, station/Classes/Application/AppState/Impl/AppStateServiceImpl.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsInteractor.swift
=> feature: Store measurements in db when app is in foreground #956

station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/View/CardView.swift, station/Resources/Strings/de.lproj/Localizable.strings, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings, station/Resources/Strings/sv.lproj/Localizable.strings
=> fix: Add no data message for sensors not seen in 10 days #654 #861

station.xcodeproj/project.pbxproj, station/Classes/Presentation/Modules/TagSettings/Submodules/DFU/View/DFUViewModel.swift, station/Classes/Presentation/Modules/TagSettings/TagSettings.storyboard, station/Classes/Presentation/Modules/TagSettings/View/Table/TagSettingsTableViewController.swift, station/Classes/Presentation/Modules/TagSettings/View/TagSettingsViewModel.swift, station/Extensions/Structs/RuuviTagBatteryStatusProvider.swift, station/Resources/Strings/de.lproj/Localizable.strings, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings, station/Resources/Strings/sv.lproj/Localizable.strings
=> feature: Add battery status information in tag settings screen #886

Packages/RuuviOntology/RuuviOntology.podspec, Packages/RuuviService/RuuviService.podspec, Podfile, Podfile.lock, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift
=> refactor: Migrate BTKit #964

Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalSettings.swift, Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Settings/Submodules/Defaults/Defaults.storyboard, station/Classes/Presentation/Modules/Settings/Submodules/Defaults/Presenter/DefaultsPresenter.swift, station/Classes/Presentation/Modules/Settings/Submodules/Defaults/View/DefaultsViewModel.swift, station/Classes/Presentation/Modules/Settings/Submodules/Defaults/View/Table/Cells/DefaultsStepperTableViewCell.swift, station/Classes/Presentation/Modules/Settings/Submodules/Defaults/View/Table/DefaultsTableViewController.swift, station/Extensions/Structs/AppStoreReviewHelper.swift, station/Resources/Strings/de.lproj/Localizable.strings, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings, station/Resources/Strings/sv.lproj/Localizable.strings
=> feature: Add defaults for app review settings for QA #600

station.xcodeproj/project.pbxproj, station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, station/Classes/Presentation/Modules/TagSettings/View/TagSettingsViewModel.swift, station/Resources/Plists/Info.plist
=> fix: Ignore duplicate measurements on tag settings screen #965

Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/Presenter/DiscoverPresenter.swift
=> fix: Hide persisted sensors from discover screen #738

station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsPresenter.swift
=> fix: Modify observer placement #909

station/Extensions/Structs/RuuviTagBatteryStatusProvider.swift
=> fix: Rectify the logic for low battery indicator #886

station/Classes/Presentation/Modules/SignIn/Presenter/SignInPresenter.swift, station/Classes/Presentation/Modules/SignIn/View/SignInViewInput.swift, station/Classes/Presentation/Modules/SignIn/View/ViewController/Helper/RuuviCodeView.swift, station/Classes/Presentation/Modules/SignIn/View/ViewController/SignInViewController.swift
=> fix: Clear codeview after failed attempt #955

Packages/RuuviDaemon/Sources/RuuviDaemon/RuuviDaemonCloudSync.swift, Packages/RuuviDaemon/Sources/RuuviDaemonCloudSync/RuuviDaemonCloudSyncWorker.swift, Packages/RuuviService/Sources/RuuviService/RuuviServiceCloudSync.swift, Packages/RuuviService/Sources/RuuviServiceCloudSync/RuuviServiceCloudSyncImpl.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/TagChartsScrollViewController.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/TagChartsViewInput.swift, station/Classes/Presentation/Modules/SignIn/Presenter/SignInPresenter.swift
- Other minor internal improvements
=> fix: Make shared sensor Gatt sync-able while in range #985

Packages/RuuviDaemon/Sources/RuuviDaemonCloudSync/RuuviDaemonCloudSyncWorker.swift, Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalSettings.swift, Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift, station/Classes/Application/AppAssembly.swift, station/Classes/Application/AppState/Impl/AppStateServiceImpl.swift, station/Classes/Application/UniversalLinks/Coordinator/Impl/UniversalLinkCoordinatormpl.swift, station/Classes/Application/UniversalLinks/Coordinator/UniversalLinkCoordinator.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/CardsViewOutput.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/CardsScrollViewController.swift
- Core refactor and improvements
=> fix: Make widget tap open the correct card #989

station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartModuleInput.swift, station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsInteractor.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsInteractorInput.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsPresenter.swift
=> fix: Improve calibration settings experience on charts screen #909

station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Router/CardsRouter.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Router/CardsRouterInput.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Router/TagChartsRouter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Router/TagChartsRouterInput.swift, station/Classes/Presentation/Modules/Menu/Menu.storyboard, station/Classes/Presentation/Modules/Menu/Presenter/MenuModuleOutput.swift, station/Classes/Presentation/Modules/Menu/Presenter/MenuPresenter.swift, station/Classes/Presentation/Modules/Menu/View/MenuViewOutput.swift, station/Classes/Presentation/Modules/Menu/View/Table/MenuTableEmbededViewController.swift, station/Resources/Strings/de.lproj/Localizable.strings, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings, station/Resources/Strings/sv.lproj/Localizable.strings
=> feature: Add menu item and localised url #993 #994

Packages/RuuviService/Sources/RuuviServiceExport/RuuviServiceExportImpl.swift, station/Classes/Application/AppAssembly.swift, station/Extensions/Structs/ExportHeadersProvider.swift
=> feature: Unify csv file #984

Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Response/RuuviCloudApiGetSettingsResponse.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Settings/RuuviCloudApiSettings.swift, Packages/RuuviOntology/Sources/RuuviOntology/Common/RuuviCloudSettings.swift, Packages/RuuviService/Sources/RuuviServiceCloudSync/RuuviServiceCloudSyncImpl.swift
=> fix: Sync resolution settings from cloud #935

Packages/RuuviService/Sources/RuuviServiceExport/RuuviServiceExportImpl.swift, station/Extensions/Structs/ExportHeadersProvider.swift
=> fix: Remove ISO timestamp column from export csv #984

station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift
=> fix: Fix an issue where language change causing unexpected behaviour

Modules/RuuviDiscover/Sources/RuuviDiscover/Resources/Discover.storyboard, station/Classes/Presentation/Modules/About/About.storyboard, station/Classes/Presentation/Modules/About/View/AboutViewController.swift, station/Classes/Presentation/Modules/Settings/Module/Settings.storyboard
- Minor tint unification on settings and discover page
=> feature: Unify about page design #1003

station/Classes/Presentation/Modules/Dashboard/Cards/Cards.storyboard, station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/CardsScrollViewController.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/View/CardView.xib, station/Classes/Presentation/Modules/Dashboard/Charts/TagCharts.storyboard, station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/TagChartsScrollViewController.swift
=> fix: Make icon size smaller and unify alert bell icon behave #1001

station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/View/CardView.xib
=> feature: Decrease gateway and BT icon size on card #1002

Modules/RuuviLocationPicker/Sources/RuuviLocationPicker/Resources/LocationPicker.storyboard, station/Classes/Presentation/Modules/About/About.storyboard, station/Classes/Presentation/Modules/About/View/AboutViewController.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Cards.storyboard, station/Classes/Presentation/Modules/Dashboard/Charts/TagCharts.storyboard, station/Classes/Presentation/Modules/LocationPicker/LocationPicker.storyboard, station/Classes/Presentation/Modules/Menu/Menu.storyboard, station/Classes/Presentation/Modules/Settings/Module/Settings.storyboard, station/Classes/Presentation/Modules/Settings/Submodules/Selection/Selection.storyboard, station/Classes/Presentation/Modules/Share/Share.storyboard, station/Classes/Presentation/Modules/Share/View/ViewController/ShareViewController.swift, station/Classes/Presentation/Modules/SignIn/SignIn.storyboard, station/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/OffsetCorrection.storyboard, station/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/View/Apple/OffsetCorrectionAppleViewController.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/Owner.storyboard, station/Classes/Presentation/Modules/TagSettings/Submodules/UpdateFirmware/UpdateFirmware.storyboard, station/Classes/Presentation/Modules/TagSettings/Submodules/UpdateFirmware/View/Apple/UpdateFirmwareAppleViewController.swift, station/Classes/Presentation/Modules/TagSettings/TagSettings.storyboard, station/Classes/Presentation/Modules/WebTagSettings/WebTagSettings.storyboard
=> feature: Unify font, text color and tint across the app #949

station/Classes/Presentation/Modules/Menu/Presenter/MenuPresenter.swift, station/Classes/Presentation/Modules/Menu/View/MenuViewOutput.swift, station/Classes/Presentation/Modules/Menu/View/Table/MenuTableEmbededViewController.swift
=> fix: Make sign in option visible after language switch #999

Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Advertisement/RuuviTagAdvertisementDaemonBTKit.swift, Packages/RuuviService/Sources/RuuviServiceCloudSync/RuuviServiceCloudSyncImpl.swift
- Improve cloud mode toggle experience
=> fix: Make cloud sync work properly for shared sensors #990

Packages/RuuviService/Sources/RuuviService/RuuviServiceMeasurement.swift, Packages/RuuviService/Sources/RuuviServiceMeasurement/RuuviServiceMeasurementImpl.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/CardsScrollViewController.swift, station/Classes/Presentation/Modules/Settings/Submodules/Unit Settings/Presenter/UnitSettingsPresenter.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/Presenter/OffsetCorrectionPresenter.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/View/Apple/OffsetCorrectionAppleViewController.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/View/OffsetCorrectionViewModel.swift
=> fix: Make resolution settings not affect offset calibration and csv file #935

Packages/RuuviDaemon/Sources/RuuviDaemon/RuuviTagAdvertisementDaemon.swift, Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Advertisement/RuuviTagAdvertisementDaemonBTKit.swift, Packages/RuuviService/Sources/RuuviServiceOwnership/RuuviServiceOwnershipImpl.swift, station.xcodeproj/project.pbxproj, station/Classes/Presentation/Modules/Dashboard/Chart/View/ChartView/TagChartView.swift, station/Classes/Presentation/Modules/Dashboard/Chart/View/ChartView/YAxisValueFormatter.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/View/Apple/OffsetCorrectionAppleViewController.swift, station/Resources/Strings/de.lproj/Localizable.strings, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings, station/Resources/Strings/sv.lproj/Localizable.strings
- Update localisation, minor fix in chart page
Card #1023
=> fix: Show correct value in offset calibration page

station/Classes/Presentation/Modules/Menu/Presenter/MenuPresenter.swift, station/Classes/Presentation/Modules/Menu/View/MenuViewOutput.swift, station/Classes/Presentation/Modules/Menu/View/Table/MenuTableEmbededViewController.swift, station/Classes/Presentation/Modules/Menu/View/Table/MenuTableViewController.swift
=> fix: Make minor improvement on menu #999

Packages/RuuviService/Sources/RuuviServiceMeasurement/RuuviServiceMeasurementImpl.swift, station/Resources/Strings/fi.lproj/Localizable.strings
=> fix: Make dew point humidity formatting according to settings #935

station/Classes/Presentation/Modules/TagSettings/View/Table/SectionHeader/TagSettingsAlertsHeaderFooterView.xib, station/Classes/Presentation/Modules/TagSettings/View/Table/SectionHeader/TagSettingsMoreInfoHeaderFooterView.xib, station/Classes/Presentation/Modules/TagSettings/View/Table/TagSettingsTableViewController.swift
=> refactor: Improve spacing in tag settings page #949

station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/View/CardView.xib
=> fix: Remove extra spacing #1034

station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/CardsScrollViewController.swift
=> fix: Stop bell blink when alert is disabled #1033

station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/TagChartsScrollViewController.swift
=> fix: Remove animation when alert is disabled #1033

station/Classes/Application/Features/FeatureToggle.swift, station/Classes/Application/Features/FeatureToggleService.swift, station/Classes/Presentation/Modules/Menu/View/Table/MenuTableEmbededViewController.swift, station/Classes/Presentation/Modules/Menu/View/Table/MenuTableViewController.swift
=> fix: Fix issue where login button was not visible after language change

Packages/RuuviService/Sources/RuuviServiceCloudSync/RuuviServiceCloudSyncImpl.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift
Rewrite the method responsible for cloud sync. This method was causing an issue where signing in onto account without cloud tags.
=> refactor: Improve cloud sync pipeline

station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/TagChartsScrollViewController.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/TagChartsViewInput.swift, station/Classes/Presentation/Modules/Dashboard/Charts/View/TagChartsViewOutput.swift, station/Resources/Strings/de.lproj/Localizable.strings, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings, station/Resources/Strings/sv.lproj/Localizable.strings
=> feature: Add alert when user tries to leave sync page #1035

station/Extensions/Structs/ExportHeadersProvider.swift
=> fix: Modify csv file header for dew point #1059

station.xcodeproj/project.pbxproj, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Router/CardsRouter.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Router/CardsRouterInput.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Router/TagChartsRouter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Router/TagChartsRouterInput.swift, station/Classes/Presentation/Modules/Menu/Menu.storyboard, station/Classes/Presentation/Modules/Menu/Presenter/MenuModuleOutput.swift, station/Classes/Presentation/Modules/Menu/Presenter/MenuPresenter.swift, station/Classes/Presentation/Modules/Menu/View/MenuViewInput.swift, station/Classes/Presentation/Modules/Menu/View/Table/MenuTableEmbededViewController.swift, station/Classes/Presentation/Modules/Menu/View/Table/MenuTableViewController.swift, station/Classes/Presentation/Modules/My Ruuvi/Assembly/MyRuuviAccountConfigurator.swift, station/Classes/Presentation/Modules/My Ruuvi/Assembly/MyRuuviAccountInitializer.swift, station/Classes/Presentation/Modules/My Ruuvi/MyRuuvi.storyboard, station/Classes/Presentation/Modules/My Ruuvi/Presenter/MyRuuviAccountModuleInput.swift, station/Classes/Presentation/Modules/My Ruuvi/Presenter/MyRuuviAccountPresenter.swift, station/Classes/Presentation/Modules/My Ruuvi/Router/MyRuuviAccountRouter.swift, station/Classes/Presentation/Modules/My Ruuvi/Router/MyRuuviAccountRouterInput.swift, station/Classes/Presentation/Modules/My Ruuvi/View/MyRuuviAccountViewController.swift, station/Classes/Presentation/Modules/My Ruuvi/View/MyRuuviAccountViewInput.swift, station/Classes/Presentation/Modules/My Ruuvi/View/MyRuuviAccountViewModel.swift, station/Classes/Presentation/Modules/My Ruuvi/View/MyRuuviAccountViewOutput.swift, station/Resources/Strings/de.lproj/Localizable.strings, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings, station/Resources/Strings/sv.lproj/Localizable.strings
- Move sign out option under this page.
- Add account delete option on this page.
=> feature:  Add my ruuvi account menu item #1019

Packages/RuuviCloud/RuuviCloud.podspec, Podfile.lock
=> Bump RuuviCloud version

station/Classes/Application/Features/FeatureToggle.swift, station/Classes/Presentation/FLEX/FLEXFeatureTogglesViewController.swift, station/Classes/Presentation/Modules/Menu/Presenter/MenuPresenter.swift, station/Classes/Presentation/Modules/Menu/View/MenuViewInput.swift, station/Classes/Presentation/Modules/Menu/View/Table/MenuTableEmbededViewController.swift, station/Classes/Presentation/Modules/Menu/View/Table/MenuTableViewController.swift, station/Resources/JSONs/FeatureToggles.json
=> fix: Remove firebase settings for showing sign in option #1066

Common/RuuviBundleUtils/RuuviBundleUtils.podspec, Common/RuuviBundleUtils/Sources/RuuviBundleUtils/RuuviBundleUtils.swift, Common/RuuviLocalization/RuuviLocalization.podspec, Modules/RuuviDiscover/Sources/RuuviDiscover/Resources/de.lproj/RuuviDiscover.strings, Modules/RuuviDiscover/Sources/RuuviDiscover/Resources/en.lproj/RuuviDiscover.strings, Modules/RuuviDiscover/Sources/RuuviDiscover/Resources/fi.lproj/RuuviDiscover.strings, Modules/RuuviDiscover/Sources/RuuviDiscover/Resources/fr.lproj/RuuviDiscover.strings, Modules/RuuviDiscover/Sources/RuuviDiscover/Resources/ru.lproj/RuuviDiscover.strings, Modules/RuuviDiscover/Sources/RuuviDiscover/Resources/sv.lproj/RuuviDiscover.strings, Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/Presenter/DiscoverPresenter.swift, Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/View/Table/DiscoverTableViewController.swift, Modules/RuuviLocationPicker/Sources/RuuviLocationPicker/VMP/View/Apple/LocationPickerAppleViewController.swift, Packages/RuuviDaemon/Sources/RuuviDaemonCloudSync/RuuviDaemonCloudSyncWorker.swift, Podfile.lock, station.xcodeproj/project.pbxproj, station/Classes/Presentation/Modules/Dashboard/Cards/View/Scroll/View/CardView.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsViewInteractor.swift, station/Classes/Presentation/Modules/SignIn/Presenter/SignInPresenter.swift, station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/View/Apple/OffsetCorrectionAppleViewController.swift, station/Extensions/String+Localization.swift
- Remove localisation library we used. Last time it was not removed properly.
- Move DB call to background thread for some cases. This is experimental. If this goes well, other places will be fixed accordingly.
- Other minor fixes here and there.
=> fix: Address the issues where device may be lagging #1078

Packages/RuuviContext/Sources/RuuviContextSQLite/SQLiteContextGRDB.swift, Packages/RuuviDaemon/Sources/RuuviDaemon/RuuviTagHeartbeatDaemon.swift, Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Heartbeat/RuuviTagHeartbeatDaemonBTKit.swift, Packages/RuuviPersistence/Sources/RuuviPersistence/RuuviPersistence.swift, Packages/RuuviPersistence/Sources/RuuviPersistenceRealm/RuuviPersistenceRealm.swift, Packages/RuuviPersistence/Sources/RuuviPersistenceSQLite/RuuviPersistenceSQLite.swift, Packages/RuuviPool/Sources/RuuviPool/RuuviPool.swift, Packages/RuuviPool/Sources/RuuviPoolCoordinator/RuuviPoolCoordinator.swift, Packages/RuuviService/Sources/RuuviServiceAuth/RuuviServiceAuthImpl.swift, Packages/RuuviService/Sources/RuuviServiceOwnership/RuuviServiceOwnershipImpl.swift, station/Classes/Presentation/Modules/TagSettings/Assembly/Table/TagSettingsTableConfigurator.swift, station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, station/Resources/Strings/de.lproj/Localizable.strings, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings, station/Resources/Strings/sv.lproj/Localizable.strings
This is experimental and we will have to see how it works out.
Also fixed an issue where sensors were listened even after deleted.
Update about page seen sensors string.
=> fix: Setup vacuum for SQL database #1172

Packages/RuuviCloud/Sources/RuuviCloud/RuuviCloudApiError.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Response/RuuviCloudApiBaseResponse.swift, Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalSettings.swift, Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalSyncState.swift, Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift, Packages/RuuviService/Sources/RuuviServiceCloudSync/RuuviServiceCloudSyncImpl.swift, station/Classes/Presentation/Modules/Dashboard/Home/Assembly/DashboardModuleFactory.swift, station/Classes/Presentation/Modules/Dashboard/Home/Presenter/DashboardPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Home/View/DashboardViewController.swift, station/Classes/Presentation/Modules/Dashboard/Home/View/DashboardViewOutput.swift, station/Classes/Presentation/Modules/My Ruuvi/Presenter/MyRuuviAccountPresenter.swift, station/Classes/Presentation/Modules/Settings/Submodules/Defaults/Presenter/DefaultsPresenter.swift, station/Extensions/Errors/RuuviCloudApiError+LocalizedError.swift
=> task: Logout user if token gets expired

Packages/RuuviService/Sources/RuuviServiceCloudSync/RuuviServiceCloudSyncImpl.swift, station.xcodeproj/project.pbxproj, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/CardsViewInput.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/CardsViewModel.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/UI/CardsLargeImageCell.swift, station/Classes/Presentation/Modules/Dashboard/Cards/View/UI/CardsViewController.swift, station/Classes/Presentation/Modules/Dashboard/Home/Presenter/DashboardPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Home/View/DashboardPlainCell.swift, station/Classes/Presentation/Modules/Dashboard/Home/View/DashboardViewInput.swift
=> Critical bug fixes

station.xcodeproj/project.pbxproj, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsViewPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Home/Presenter/DashboardPresenter.swift
- Crash on dashboard and sensor cards.
- Silent crash on tag charts and settings.
=> fix: Address repetitive crashes from crashlogs

Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Response/RuuviCloudApiGetAlertsResponse.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Response/RuuviCloudApiGetSensorsDenseResponse.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Response/RuuviCloudApiUserResponse.swift, Packages/RuuviCloud/Sources/RuuviCloudPure/RuuviCloudPure.swift, Packages/RuuviContext/Sources/RuuviContextSQLite/SQLiteContextGRDB.swift, Packages/RuuviDaemon/Sources/RuuviDaemonCloudSync/RuuviDaemonCloudSyncWorker.swift, Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Properties/RuuviTagPropertiesDaemonBTKit.swift, Packages/RuuviNotification/Sources/RuuviNotificationLocal/RuuviNotificationLocalImpl.swift, Packages/RuuviOntology/Sources/RuuviOntology/Mappers/RuuviTag+RuuviTagSensor.swift, Packages/RuuviOntology/Sources/RuuviOntology/Sensor/CloudSensor.swift, Packages/RuuviOntology/Sources/RuuviOntology/Sensor/CloudSensorDense.swift, Packages/RuuviOntology/Sources/RuuviOntology/Sensor/CloudSensorSubscription.swift, Packages/RuuviOntology/Sources/RuuviOntology/Sensor/RuuviTag/RuuviTagSensor.swift, Packages/RuuviOntology/Sources/RuuviOntology/Sensor/Sensor.swift, Packages/RuuviOntology/Sources/RuuviOntologyRealm/RuuviTagRealm+RuuviTagSensor.swift, Packages/RuuviOntology/Sources/RuuviOntologySQLite/RuuviTagSQLite.swift, Packages/RuuviPersistence/Sources/RuuviPersistenceRealm/RuuviPersistenceRealm.swift, Packages/RuuviPersistence/Sources/RuuviPersistenceSQLite/RuuviPersistenceSQLite.swift, Packages/RuuviService/Sources/RuuviService/RuuviServiceCloudSync.swift, Packages/RuuviService/Sources/RuuviServiceCloudSync/RuuviServiceCloudSyncImpl.swift, ruuvi-widgets/View Model/WidgetViewModel.swift, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Home/Presenter/DashboardPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Home/View/DashboardImageCell.swift, station/Classes/Presentation/Modules/Dashboard/Home/View/DashboardIndicatorView.swift, station/Classes/Presentation/Modules/Dashboard/Home/View/DashboardPlainCell.swift, station/Classes/Presentation/Modules/Dashboard/Home/View/DashboardViewController.swift, station/Classes/Presentation/Modules/TagSettings/View/UI/TagSettingsViewController.swift
- Replaced /user and /alerts endpoint calls with /sensors-dense
- Skip /get calls for the sensors doesn't support history fetching.
- Store sharee users email on local database.
=> task: Optimise cloud calls #1345

Packages/RuuviDaemon/Sources/RuuviDaemonCloudSync/RuuviDaemonCloudSyncWorker.swift, Packages/RuuviService/Sources/RuuviService/RuuviServiceOwnership.swift, Packages/RuuviService/Sources/RuuviServiceOwnership/RuuviServiceOwnershipImpl.swift, station/Classes/Presentation/Modules/Share/Assembly/ShareConfigurator.swift, station/Classes/Presentation/Modules/Share/Presenter/SharePresenter.swift, station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/Presenter/OwnerPresenter.swift, station/Classes/Presentation/Modules/TagSettings/View/TagSettingsViewModel.swift, station/Classes/Presentation/Modules/TagSettings/View/TagSettingsViewOutput.swift, station/Classes/Presentation/Modules/TagSettings/View/UI/TagSettingsViewController.swift, station/Resources/Strings/de.lproj/Localizable.strings, station/Resources/Strings/en.lproj/Localizable.strings, station/Resources/Strings/fi.lproj/Localizable.strings, station/Resources/Strings/fr.lproj/Localizable.strings, station/Resources/Strings/ru.lproj/Localizable.strings, station/Resources/Strings/sv.lproj/Localizable.strings
- Optimise endpoint calls for share view
=> task: Add shared count in tag settings #1331 #1332

station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, station/Classes/Presentation/Modules/TagSettings/View/TagSettingsViewModel.swift, station/Classes/Presentation/Modules/TagSettings/View/UI/TagSettingsViewController.swift, station/Extensions/UnitPressure+Extension.swift
=> task: Modify pressure alert limit threshold #1438

Packages/RuuviCloud/RuuviCloud.podspec, Packages/RuuviCloud/Sources/RuuviCloud/RuuviCloudApiError.swift, Packages/RuuviCloud/Sources/RuuviCloud/RuuviCloudApiErrorCode.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Request/RuuviCloudApiPostAlertRequest.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Request/RuuviCloudApiPostSettingRequest.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Request/RuuviCloudApiSensorUpdateRequest.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Response/RuuviCloudApiBaseResponse.swift, Packages/RuuviCloud/Sources/RuuviCloudPure/RuuviCloudPure.swift, Packages/RuuviService/Sources/RuuviServiceCloudSync/RuuviServiceCloudSyncImpl.swift, Podfile.lock, station.xcodeproj/project.pbxproj, station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, station/Classes/Presentation/Modules/Dashboard/Home/Presenter/DashboardPresenter.swift, station/Classes/Presentation/Modules/Settings/Submodules/Unit Settings/Presenter/UnitSettingsPresenter.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/Presenter/OwnerPresenter.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/View/OwnerViewController.swift, station/Classes/Presentation/Modules/TagSettings/Submodules/Owner/View/OwnerViewInput.swift, station/Extensions/Errors/RuuviCloudApiError+LocalizedError.swift
- Add timestamp to endpoint /settings, /update, /alerts
- Improve pending request execution method.
- Improve cloud sync queue error decoding that also affects the sensor ownership claim view.
=> fix: Update ruuvi cloud module #1450 #746

station.xcodeproj/project.pbxproj, station/Classes/Presentation/Modules/TagSettings/View/UI/TagSettingsViewController.swift
=> fix: Fix potential crash and offset correction not being tappable #1487 #1475

station.xcodeproj/project.pbxproj, station/Classes/Routers/AppRouter.swift, station/Resources/Plists/DevInfo.plist, station/Resources/Plists/Info.plist
=> fix: Sensor card back button shows wrong page

Packages/RuuviDaemon/Sources/RuuviDaemonCloudSync/RuuviDaemonCloudSyncWorker.swift, station.xcodeproj/project.pbxproj, station/Classes/Application/AppState/Impl/AppStateServiceImpl.swift, station/Resources/Plists/DevInfo.plist, station/Resources/Plists/Info.plist
=> Import cloud sync behaviour

.gitignore, Makefile, scripts/install/install_xcodegen.sh
Added script to install xcodegen, so `make` works even without `brew install xcodegen`
=> Xcodegen tool installation if needed

project_frameworks.yml, project_spm.yml, ruuvi-widgets/Assembly/WidgetAssembly.swift, ruuvi-widgets/Info.plist, widget_frameworks.yml, widget_spm.yml
Implements xcodeproj gen for Widget
=> Xcodegen for Widget target

.gitignore, project_frameworks.yml, project_spm.yml, scripts/build/load_keystore.sh
Only on Archive for Release configuration loads secrects
=> Load Keystore PostBuild script

.gitignore, intents/Info.plist, intents_frameworks.yml, intents_spm.yml, pnservice.yml, pnservice/Info.plist, project_frameworks.yml, project_spm.yml, scripts/build/load_keystore.sh
Implements adding PNService and Intents targets to xcodeproj generated with xcodegen.
=> Intents and PNService targets from xcodegen

Makefile, pnservice.yml, project_frameworks.yml, project_spm.yml, scripts/build/generate_l10n.sh, scripts/install/install_swiftgen.sh, scripts/install/install_xcodegen.sh, widget_frameworks.yml
=> Implement localization swiftgen step

widget_spm.yml
=> Fix SPM build

project_frameworks.yml, project_spm.yml, station.xcodeproj/project.pbxproj, station/Classes/Application/AppDelegate.swift, station/Classes/Presentation/Assembly/PresentationAssembly.swift, station/Classes/Presentation/FLEX/FeatureTogglesViewController.swift, station/Classes/Presentation/Modules/Settings/Module/Router/SettingsRouter.swift, station/Extensions/UIWindow+Shake.swift
Implements support for FLEX in DEBUG for spm/framworks
=> FLEX support for spm/framework project

station/Resources/Plists/iOSDeviceModelMapping.plist
Fills missing models in device model mapping plist
=> Fill the iOS device model mapping PLIST

.github/workflows/firebase_frameworks.yml
Adds a changelog to Firebase Distribution deploy.
=> Add ChangeLog to firebase [frameworks] workflow

project_frameworks.yml
=> Disable Lint script dependency analysis

.github/workflows/pr_checks.yml, pnservice/NotificationService.swift
Implements linter checks on the PR.
=> Add pr_checks GitHub Actions workflow

Common/RuuviPresenters/Sources/RuuviPresenters/Activity/RuuviLogo/ActivityPresenterRuuviLogo.swift, Packages/RuuviCloud/Sources/RuuviCloud/RuuviCloud.swift, Packages/RuuviCloud/Sources/RuuviCloudPure/RuuviCloudPure.swift, station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift
- Shows cloud request state (loading/success/failed) when a setting is changed or sensor name is updated.
=> feature: Show cloud saving state on sensor settings #1600

Apps/RuuviStation/Sources/Classes/Application/AppAssembly.swift, Apps/RuuviStation/Sources/Classes/Application/AppState/Impl/AppStateServiceImpl.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/Interactor/DashboardInteractor.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/View/Apple/OffsetCorrectionAppleViewController.swift, Apps/RuuviStation/Widgets/Sources/Assembly/WidgetAssembly.swift, Packages/RuuviContext/Sources/RuuviContextSQLite/SQLiteContextGRDB.swift, Packages/RuuviMigration/Sources/RuuviMigrationImpl/toSQLite/MigrationManagerToSQLite.swift, Packages/RuuviMigration/Sources/RuuviMigrationImpl/toVIPER/MigrationManagerToVIPER.swift, Packages/RuuviPersistence/Sources/RuuviPersistenceRealm/RuuviPersistenceRealm.swift, Packages/RuuviPersistence/Sources/RuuviPersistenceSQLite/RuuviPersistenceSQLite.swift, Packages/RuuviReactor/Sources/RuuviReactorImpl/RuuviReactorCombine/RuuviTagLastRecordSubjectCombine.swift, Packages/RuuviReactor/Sources/RuuviReactorImpl/RuuviReactorCombine/RuuviTagLatestRecordSubjectCombine.swift, Packages/RuuviReactor/Sources/RuuviReactorImpl/RuuviReactorCombine/RuuviTagRecordSubjectCombine.swift, Packages/RuuviReactor/Sources/RuuviReactorImpl/RuuviReactorCombine/RuuviTagSubjectCombine.swift, Packages/RuuviReactor/Sources/RuuviReactorImpl/RuuviReactorCombine/SensorSettingsCombine.swift, Packages/RuuviReactor/Sources/RuuviReactorImpl/RuuviReactorImpl.swift, Packages/RuuviService/Sources/RuuviServiceCloudNotification/RuuviServiceCloudNotificationImpl.swift, Packages/RuuviService/Sources/RuuviServiceFactory/RuuviServiceFactory.swift
Motivation: no need for project without dev pods
=> Remove #if canImport()

Apps/RuuviStation/Sources/Classes/Presentation/Modules/About/View/AboutViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Menu/View/Table/MenuTableEmbededViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Menu/View/Table/MenuTableViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/My Ruuvi/View/MyRuuviAccountViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Module/View/Table/SettingsTableViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Chart/View/Table/ChartSettingsTableViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Defaults/View/DefaultsViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Defaults/View/Table/DefaultsTableViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Heartbeat/View/HeartbeatViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Heartbeat/View/Table/HeartbeatTableViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Selection/View/Table/SelectionTableViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Unit Settings/View/Table/UnitSettingsTableViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Share/View/ViewController/ShareViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/View/Apple/OffsetCorrectionAppleViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/Owner/View/OwnerViewController.swift
=> Fix colors on Storyboards

Common/RuuviPresenters/target.yml
=> Fix dependencies of RuuviPresenters

Common/RuuviPresenters/target.yml
=> Fix dependencies of RuuviPresenters (#1786)

Packages/RuuviOntology/Sources/RuuviOntologySQLite/SensorSettingsSQLite.swift
Fixes typo in column creation logic
=> Fix type in table creation

Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/Presenter/DiscoverPresenter.swift, Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/View/DiscoverViewInput.swift, Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/View/DiscoverViewOutput.swift, Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/View/Table/DiscoverTableViewController.swift, Modules/RuuviFirmware/Sources/RuuviFirmware/FirmwarePresenter.swift, Modules/RuuviFirmware/Sources/RuuviFirmware/RuuviFirmware.swift, Packages/RuuviReactor/Sources/RuuviReactorImpl/RuuviReactorImpl.swift
Implements firmware update alert when adding df3 tag
=> Firmware update popup for df3

Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/Presenter/DiscoverPresenter.swift, Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/View/DiscoverViewInput.swift, Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/View/DiscoverViewOutput.swift, Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/View/Table/DiscoverTableViewController.swift, Modules/RuuviFirmware/Sources/RuuviFirmware/FirmwarePresenter.swift, Modules/RuuviFirmware/Sources/RuuviFirmware/RuuviFirmware.swift, Packages/RuuviDFU/Sources/RuuviDFU/RuuviDFUError.swift, Packages/RuuviDFU/Sources/RuuviDFUImpl/DfuFlasher.swift, Packages/RuuviDFU/target.yml, Packages/RuuviOntology/Sources/RuuviOntologySQLite/SensorSettingsSQLite.swift, Packages/RuuviReactor/Sources/RuuviReactorImpl/RuuviReactorImpl.swift
- df3 firmware upgrade on Discover
=> Release 2.5.2 [Firmware Upgrade for df3]

.github/workflows/firebase.yml
For Alpha builds use dev branch in station.localization
=> Quiet xcodebuild and dev branch for localization

.github/workflows/firebase.yml
For Alpha builds use dev branch in station.localization
=> Quiet xcodebuild and dev branch for localization (#1794)

Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Cards/View/CardsViewModel.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/Presenter/DashboardPresenter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/View/DashboardViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/View/DashboardViewInput.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/View/DashboardViewOutput.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/View/TagSettingsViewInput.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/View/UI/TagSettingsViewController.swift, Packages/RuuviCloud/Sources/RuuviCloud/RuuviCloud.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/Helpers/RuuviCloudApiHelper.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Request/RuuviCloudApiPostSettingRequest.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Response/RuuviCloudApiGetSettingsResponse.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Settings/RuuviCloudApiSettings.swift, Packages/RuuviCloud/Sources/RuuviCloudPure/RuuviCloudPure.swift, Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalSettings.swift, Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift, Packages/RuuviOntology/Sources/RuuviOntology/Common/DashboardSortingType.swift, Packages/RuuviOntology/Sources/RuuviOntology/Common/RuuviCloudSettings.swift, Packages/RuuviService/Sources/RuuviService/RuuviServiceAppSettings.swift, Packages/RuuviService/Sources/RuuviServiceAppSettings/RuuviServiceAppSettingsImpl.swift, Packages/RuuviService/Sources/RuuviServiceCloudSync/RuuviServiceCloudSyncImpl.swift
=> feature: Implement drag and drop for cards on dashboard #1632 (#1796)

Apps/RuuviStation/NotificationService/Sources/NotificationService.swift, Apps/RuuviStation/NotificationService/target.yml, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/View/UI/TagChartsViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/View/Apple/OffsetCorrectionAppleViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/View/UI/TagSettingsViewController.swift, Apps/RuuviStation/Sources/Extensions/HumidityUnit+Localization.swift, Apps/RuuviStation/Sources/Extensions/Structs/ExportHeadersProvider.swift, Apps/RuuviStation/Sources/Station.entitlements, Common/RuuviLocalization/Templates/strings-swift5.stencil, Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift
fixes https://github.com/ruuvi/com.ruuvi.station.ios/issues/1805
Implements localization for notifications except ovement and offline
=> NotificationService localization fixes

Apps/RuuviStation/NotificationService/Sources/NotificationService.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/View/UI/TagChartsViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/View/Apple/OffsetCorrectionAppleViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/View/UI/TagSettingsViewController.swift, Apps/RuuviStation/Sources/Extensions/HumidityUnit+Localization.swift, Apps/RuuviStation/Sources/Extensions/Structs/ExportHeadersProvider.swift, Common/RuuviLocalization/Templates/strings-swift5.stencil, Common/RuuviLocalization/target.yml
=> Fix localizations in PN service

.github/workflows/testflight.yml
Implements workflow to upload build to TestFlight
=> TestFlight workflow

Apps/RuuviStation/Intents/target.yml, Apps/RuuviStation/NotificationService/target.yml, Apps/RuuviStation/Widgets/target.yml, Common/RuuviLocalization/target.yml, Packages/RuuviCloud/target.yml, Packages/RuuviContext/target.yml, Packages/RuuviLocal/target.yml, Packages/RuuviOntology/target.yml, Packages/RuuviPersistence/target.yml, Packages/RuuviPool/target.yml, Packages/RuuviUser/target.yml
In order to distribute to TestFlight
=> Respect app extension only API requirement

Common/RuuviPresenters/Sources/RuuviPresenters/Activity/RuuviLogo/ActivityPresenterRuuviLogo.swift
Increase min screen on time for toast to 1.5 seconds from 1 second.
=> fix: Fix UI glitch after toast is dismissed #1600

Common/RuuviPresenters/Sources/RuuviPresenters/Activity/RuuviLogo/ActivityPresenterRuuviLogo.swift
Fix UI glitch after toast is dismissed #1600
=> 2.6.0 Alpha 

Modules/RuuviFirmware/Sources/RuuviFirmware/FirmwareInteractor.swift, Modules/RuuviFirmware/Sources/RuuviFirmware/FirmwarePresenter.swift, Modules/RuuviFirmware/Sources/RuuviFirmware/RuuviFirmwareBuilder.swift, Modules/RuuviFirmware/Sources/RuuviFirmware/SwiftUI/FirmwareView.swift, Modules/RuuviFirmware/Sources/RuuviFirmware/SwiftUI/FirmwareViewModel.swift
Implements battery charge check on Firmware upgrade process on Discover
=> Add battery level check on FW upgrade from Discover

Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/View/NoSensorView.swift
=> Fix signed in initial empty screen

Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/View/NoSensorView.swift
=> Fix signed in initial empty screen (#1829)

Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/Presenter/DashboardPresenter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/View/DashboardViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/View/DashboardViewInput.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/View/NoSensorView.swift
fixes #1828 with spec from #1634
=> Fix signed in initial empty screen (#1831)

Packages/RuuviOntology/Sources/RuuviOntologySQLite/RuuviTagSQLite.swift
=> Dont abort if same RuuviTag is added by id - just replace it

Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalIDs.swift, Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalIDsUserDefaults.swift, Packages/RuuviOntology/Sources/RuuviOntologySQLite/RuuviTagSQLite.swift, Packages/RuuviService/Sources/RuuviServiceAuth/RuuviServiceAuthImpl.swift, Packages/RuuviService/Sources/RuuviServiceOwnership/RuuviServiceOwnershipImpl.swift
- fixes assertionFailure on logout
- prevent from SQLite error
=> Release 2.6.0

Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Properties/RuuviTagPropertiesDaemonBTKit.swift
E.g. the Ruuvi Tag could change its UUID because of update with nRF tools
=> Listen to UUID updates for given MAC

Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Properties/RuuviTagPropertiesDaemonBTKit.swift, Packages/RuuviOntology/Sources/RuuviOntology/Sensor/RuuviTag/RuuviTagSensor.swift
To ensure we are listening to the correct one
=> Update in SQLite the luid of a sensor

Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Properties/RuuviTagPropertiesDaemonBTKit.swift, Packages/RuuviOntology/Sources/RuuviOntology/Sensor/RuuviTag/RuuviTagSensor.swift
To ensure we are listening to the correct one
=> Update in SQLite the luid of a sensor (#1843)

Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/Helpers/CustomXAxisRenderer.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/Helpers/CustomYAxisRenderer.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/Helpers/TagChartsHelper.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/Helpers/XAxisValueFormatter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/Helpers/YAxisValueFormatter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsViewPresenter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/View/TagChartsViewInput.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/View/TagChartsViewModel.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/View/UI/TagChartsMarkerView.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/View/UI/TagChartsView.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/View/UI/TagChartsViewController.swift, Apps/RuuviStation/target.yml, project.yml
Motivation: use SwiftUI charts without conflicts in namespaces
=> Upgrade Charts to 5+

Apps/RuuviStation/Widgets/Sources/View Model/WidgetViewModel.swift
fixes #1850. Motivation: avoid confusing users
=> Show last seen date on widget

.swiftgen.assets.yml
=> 2.6.0 fix swiftgen

Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Module/View/Table/SettingsTableViewController.swift
Motivation: report by Marko that Defaults are not visible
=> Use DEBUG to control debug secitions in menu

Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Module/View/Table/SettingsTableViewController.swift
Motivation: report by Marko that Defaults are not visible
=> Use DEBUG to control debug secitions in menu (#1868)

Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Heartbeat/RuuviTagHeartbeatDaemonBTKit.swift
Reason: saved date was accessed from different threads. Made it on sync queue.
=> Fix Heartbeat Daemon crash

.github/workflows/testflight.yml, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/DFU/View/DFUViewModel.swift
Motivation: use crashlytics with TF builds
=> Upload dSyms on TestFlight build upload

.github/workflows/testflight.yml, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/DFU/View/DFUViewModel.swift
* Upload dSyms on TestFlight build upload Motivation: use crashlytics with TF builds
* fix warning lint
=> Upload dSyms on TestFlight build upload (#1880)

.github/workflows/firebase.yml, .github/workflows/testflight.yml
dSYMs are located in archive, not in exported ipa folder
=> Upload dSYMs fix (#1883)

.github/workflows/firebase.yml, .github/workflows/testflight.yml
=> Fix Firebase call in upload dSYM

.github/workflows/firebase.yml, .github/workflows/testflight.yml
=> Fix Firebase call in upload dSYM (#1885)

.github/workflows/firebase.yml, .github/workflows/testflight.yml
=> Fix Firebase dSYM upload

.github/workflows/firebase.yml, .github/workflows/testflight.yml
=> Fix Firebase dSYM upload (#1887)

.github/workflows/firebase.yml, .github/workflows/testflight.yml, Apps/RuuviStation/target.yml, scripts/build/upload_dsyms.sh
=> Upload dSYM using recommended way

Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Heartbeat/Presenter/HeartbeatPresenter.swift
=> Save heartbeats toggle fix (#1901)

Apps/RuuviStation/Sources/Classes/Presentation/FLEX/FeatureTogglesViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Chart/View/Table/ChartSettingsTableViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Defaults/View/Table/DefaultsTableViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Heartbeat/View/Table/HeartbeatTableViewController.swift
=> Fix switch coloring

Apps/RuuviStation/Sources/Classes/Presentation/FLEX/FeatureTogglesViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/Presenter/DashboardPresenter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Chart/View/Table/ChartSettingsTableViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Defaults/View/Table/DefaultsTableViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Heartbeat/View/Table/HeartbeatTableViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Notifications/View/UI/NotificationsSettingsSwitchCell.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Notifications/View/UI/NotificationsSettingsTextCell.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Ruuvi Cloud/View/UI/RuuviCloudTableViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Selection/View/Table/SelectionTableViewController.swift, Apps/RuuviStation/Sources/Extensions/Classess/RuuviLinkTextView.swift
=> Fix several styling issues

Apps/RuuviStation/Sources/Classes/Presentation/Modules/SignIn/View/UI/Helper/RuuviCodeTextField.swift
Not only move cursor but also clear the text
=> Clear letter on RuuviCodeView on backspace

.github/workflows/firebase.yml, Apps/RuuviStation/Sources/Classes/Application/AppAssembly.swift, Apps/RuuviStation/Sources/Classes/ErrorReporter/CrashlyticsErrorReporter.swift, Packages/RuuviAnalytics/Sources/RuuviAnalytics/RuuviErrorReporter.swift, Packages/RuuviReactor/Sources/RuuviReactor/RuuviReactorFactory.swift, Packages/RuuviReactor/Sources/RuuviReactorImpl/RuuviReactorCombine/RuuviTagLastRecordSubjectCombine.swift, Packages/RuuviReactor/Sources/RuuviReactorImpl/RuuviReactorCombine/RuuviTagLatestRecordSubjectCombine.swift, Packages/RuuviReactor/Sources/RuuviReactorImpl/RuuviReactorCombine/RuuviTagRecordSubjectCombine.swift, Packages/RuuviReactor/Sources/RuuviReactorImpl/RuuviReactorCombine/RuuviTagSubjectCombine.swift, Packages/RuuviReactor/Sources/RuuviReactorImpl/RuuviReactorCombine/SensorSettingsCombine.swift, Packages/RuuviReactor/Sources/RuuviReactorImpl/RuuviReactorFactoryImpl.swift, Packages/RuuviReactor/Sources/RuuviReactorImpl/RuuviReactorImpl.swift, Packages/RuuviReactor/target.yml, project.yml
Motivation: address GRDB crashes.
Reimplements Reactor observation logic with GRDB 6 API.
=> Upgrade GRDB to version 6+

.github/workflows/testflight.yml
Motivation: smoother release process
=> Trigger TestFlight builds on push/pr/dispatch

Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/Presenter/OffsetCorrectionPresenter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/View/OffsetCorrectionViewModel.swift, Apps/RuuviStation/Widgets/Sources/Model/Model+Extension.swift, Packages/RuuviOntology/Sources/RuuviOntology/Sensor/SensorSettings.swift, Packages/RuuviOntology/Sources/RuuviOntologySQLite/SensorSettingsSQLite.swift, Packages/RuuviPersistence/Sources/RuuviPersistenceSQLite/RuuviPersistenceSQLite.swift, Packages/RuuviReactor/Sources/RuuviReactorImpl/RuuviReactorCombine/SensorSettingsCombine.swift
=> Eliminate Offset Dates

Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsViewPresenter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/Presenter/DashboardPresenter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Advertisement/RuuviTagAdvertisementDaemonBTKit.swift, Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Heartbeat/RuuviTagHeartbeatDaemonBTKit.swift, Packages/RuuviPersistence/Sources/RuuviPersistenceSQLite/RuuviPersistenceSQLite.swift, Packages/RuuviReactor/Sources/RuuviReactorImpl/RuuviReactorImpl.swift
What: fixed blinky chat switch issue by making explicit that initial sensor settings load should not reload charts
=> Fix flaky chart

Packages/RuuviReactor/Sources/RuuviReactorImpl/RuuviReactorCombine/RuuviTagLatestRecordSubjectCombine.swift
By ensuring latest record update event happens only for latest record
=> Fix old values shown on dashboard

Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/View/Table/DiscoverTableViewController.swift
To address crashes on Discover
=> Fix obvious layout issues

Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/Helpers/TagChartsHelper.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsViewPresenter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/View/UI/TagChartsView.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/View/UI/TagChartsViewController.swift, Common/RuuviLocalization/Sources/Resources/RuuviColors.xcassets/GraphAlertColor.colorset/Contents.json
Only Relative Humidity is supported for Humidity
=> Limits on charts

Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/View/UI/TagSettingsAlertConfigCell.swift
Make it alert color outside the range
=> Color on RangeSeekSlider

Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/Helpers/TagChartsHelper.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsViewPresenter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/View/TagChartsViewInput.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/View/UI/TagChartsCollectionViewCell.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/View/UI/TagChartsCollectionViewFlowLayout.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/View/UI/TagChartsView.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/View/UI/TagChartsViewController.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Defaults/Presenter/DefaultsPresenter.swift, Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalSettings.swift, Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift
Disable the feature now since it doesn't work properly now.
Also add a feature flag for improved chart rendering.
=> task: Put show alert range settings under feature flag #1547

Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/View/UI/TagSettingsBackgroundSelectionView.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/View/UI/TagSettingsBasicCell.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/View/UI/TagSettingsViewController.swift
Remove the button and text from sensor settings related to background image and move the settings to a button instead like Android
=> task: Unify background selection with Android #1947

Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/View/DashboardCell.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/View/DashboardImageCell.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/View/DashboardPlainCell.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/View/DashboardViewController.swift
Add move up down in the context menu for sensor card on dashboard
=> task: Add move up/down option on dashboard #2019

Apps/RuuviStation/Sources/Classes/Application/AppDelegate.swift, Apps/RuuviStation/Sources/Classes/Application/AppState/AppStateService.swift, Apps/RuuviStation/Sources/Classes/Application/AppState/Impl/AppStateServiceImpl.swift, Apps/RuuviStation/Sources/Classes/Application/UniversalLinks/Coordinator/Impl/UniversalLinkCoordinatormpl.swift, Apps/RuuviStation/Sources/Classes/Application/UniversalLinks/Router/Impl/UniversalLinkRouterImpl.swift, Apps/RuuviStation/Sources/Classes/Application/UniversalLinks/Router/UniversalLinkRouter.swift, Apps/RuuviStation/Sources/Classes/Routers/AppRouter.swift
App crashes if widget is tapped when app is in killed state.
=> fix: [iOS 18] Tapping widgets may crash the app #2099

Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/Presenter/DashboardPresenter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Share/Assembly/ShareConfigurator.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Share/Presenter/SharePresenter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/View/TagSettingsViewInput.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/View/UI/TagSettingsViewController.swift, Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Response/RuuviCloudApiGetSensorsDenseResponse.swift, Packages/RuuviContext/Sources/RuuviContextSQLite/SQLiteContextGRDB.swift, Packages/RuuviOntology/Sources/RuuviOntology/Sensor/CloudSensorSubscription.swift, Packages/RuuviOntology/Sources/RuuviOntologySQLite/RuuviCloudSensorSubscriptionSQLite.swift, Packages/RuuviPersistence/Sources/RuuviPersistence/RuuviPersistence.swift, Packages/RuuviPersistence/Sources/RuuviPersistenceSQLite/RuuviPersistenceSQLite.swift, Packages/RuuviPool/Sources/RuuviPool/RuuviPool.swift, Packages/RuuviPool/Sources/RuuviPoolCoordinator/RuuviPoolCoordinator.swift, Packages/RuuviService/Sources/RuuviServiceCloudSync/RuuviServiceCloudSyncImpl.swift
- Also fixes the issue where we showed hardcoded max share count.
=> task: Create new table for storing sensor subscription data #1740

Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Background/Assembly/BackgroundSelectionModuleFactory.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Background/Presenter/BackgroundSelectionPresenter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Defaults/Presenter/DefaultsPresenter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Defaults/View/DefaultsViewModel.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Defaults/View/Table/Cells/DefaultsStepperTableViewCell.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Defaults/View/Table/DefaultsTableViewController.swift, Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalSettings.swift, Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift, Packages/RuuviService/Sources/RuuviService/RuuviServiceSensorProperties.swift, Packages/RuuviService/Sources/RuuviServiceSensorProperties/RuuviServiceSensorPropertiesImpl.swift
Default value is: 40% compression down from 60%
=> task: Make image compression level configurable from flags #2128

Packages/RuuviNotifier/Sources/RuuviNotifierImpl/RuuviNotifierImpl+Process.swift
Follows the spec from github issue.
=> task: Unify offline alerts with Android #2150

Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Defaults/Presenter/DefaultsPresenter.swift, Apps/RuuviStation/Sources/Extensions/Structs/ExportHeadersProvider.swift, Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalSettings.swift, Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift, Packages/RuuviService/Sources/RuuviService/RuuviServiceExport.swift, Packages/RuuviService/Sources/RuuviServiceExport/RuuviServiceExportImpl.swift
Disabled by default and included for mainly debug purpose
=> task: Include data source in history export #2161

Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsViewInteractor.swift
Make sure sensors without measurement do not call history endpoint
=> fix: Optimise history calls #2165

Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Cards/View/CardsViewModel.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/Presenter/DashboardPresenter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsAlertConstants.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/View/TagSettingsViewModel.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/View/UI/TagSettingsViewController.swift, Apps/RuuviStation/Sources/Extensions/String+Replace.swift, Apps/RuuviStation/Sources/Extensions/Structs/RuuviNotifierTitlesImpl.swift, Packages/RuuviNotification/Sources/RuuviNotification/RuuviNotificationLocal.swift, Packages/RuuviNotification/Sources/RuuviNotificationLocal/RuuviNotificationLocalImpl.swift, Packages/RuuviNotifier/Sources/RuuviNotifier/RuuviNotifier.swift, Packages/RuuviNotifier/Sources/RuuviNotifierImpl/RuuviNotifierImpl+Process.swift, Packages/RuuviOntology/Sources/RuuviOntology/Alert/AlertType.swift, Packages/RuuviOntology/Sources/RuuviOntology/Common/RuuviCloudAlert.swift, Packages/RuuviOntology/Sources/RuuviOntologySQLite/RuuviTagDataSQLite.swift, Packages/RuuviOntology/Sources/RuuviOntologySQLite/RuuviTagLatestDataSQLite.swift, Packages/RuuviService/Sources/RuuviService/RuuviServiceAlert.swift, Packages/RuuviService/Sources/RuuviServiceAlert/AlertPersistence/AlertPersistence.swift, Packages/RuuviService/Sources/RuuviServiceAlert/AlertPersistence/UserDefaults/AlertPersistenceUserDefaults.swift, Packages/RuuviService/Sources/RuuviServiceAlert/RuuviServiceAlertImpl.swift
Hide alerts when sensor is not present #2196
Fix jumpy menu on alerts #2121
=> task: Support alerts for E0 #2184

.github/workflows/firebase.yml, .github/workflows/testflight.yml
This reverts commit 0001f50923e841fe9483789f25aa833c62fd3610.
=> Revert "task: Update GA workflow MacOS and Xcode version (#2219)"

Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/View/UI/TagChartsMarkerView.swift
For some devices it can go beyond top bound. This commit prevent that and keeps the box always inside chart view.
=> fix: Keep chart marker box inside parent view

Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/View/UI/TagChartsViewInternal.swift, Packages/RuuviService/Sources/RuuviServiceMeasurement/RuuviServiceMeasurementImpl.swift
- Change pm resolution to 0.1
- When graph is scaled do not move graph with latest value
=> fix: Chart fixes

Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Advertisement/RuuviTagAdvertisementDaemonBTKit.swift, Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Heartbeat/RuuviTagHeartbeatDaemonBTKit.swift, Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Properties/RuuviTagPropertiesDaemonBTKit.swift, Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift
The crashes from the testflight were not reproducible, but refactored the faulty area based on the crash log to prevent the cases.
=> refactor: Potentially fix several crashes

Apps/RuuviStation/Sources/Classes/Presentation/Model/RuuviTagCardSnapshotDataBuilder.swift, Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsViewPresenter.swift, Packages/RuuviService/Sources/RuuviService/RuuviServiceMeasurement.swift, Packages/RuuviService/Sources/RuuviServiceExport/RuuviServiceExportImpl.swift, Packages/RuuviService/Sources/RuuviServiceMeasurement/RuuviServiceMeasurementImpl.swift
Removed voc and nox.
Used 1 decimal resolution for calculation.
No decimal visible on dashboard or cards but graph shows decimal resolution for data plot.
=> task: AQI logic update
