- station/Classes/Model/Ontology/Identifier/Identifier.swift
Hey @viikufa. 
Here https://github.com/ruuvi/com.ruuvi.station.ios/commit/c1756bb9b4ad9ed4559e81a5495adc24cdb459f5 you've introduced macId colon crop. Could you please verify that we can get rid of this ambiguity in MAC address representation>
> Fix mac address ambiguity

- Podfile
- Podfile.lock
- station.xcodeproj/project.pbxproj
- station/Classes/Application/AppAssembly.swift
- station/Classes/Application/AppAssemblyConstants.swift
- station/Classes/Presentation/Assembly/Presentation.plist
- station/Classes/Presentation/Assembly/PresentationAssembly.swift
- station/Classes/Presentation/Assembly/PresentationConstants.swift
- station/Classes/Presentation/Modules/Dashboard/Cards/Assembly/Scroll/CardsScrollConfigurator.swift
- station/Classes/Presentation/Modules/Dashboard/Charts/Assembly/Scroll/TagChartsScrollConfigurator.swift
- station/Resources/Plists/Networking.plist
Remove the pod for SwinjectPropertyLoader and fetch required values manually from the plist.
Requires changes to com.ruuvi.station.ios.keystore.git repo and should not be merged before those changes are merged.
> Remove SwinjectPropertyLoader

- fastlane/Fastfile
In the last two builds there has been no readme file to remove, so the build has crashed. This MR comments out the removal of readme, so builds can finish and can be tested.
> Comment out removal of readme artifact in fastlane.

- Packages/RuuviService/Sources/RuuviServiceMeasurement/RuuviServiceMeasurementImpl.swift
humidityFormatter used for humidityOffsetCorrectionString to get the value localized.
Not sure if the calibration unit should change with settings, the raised issue concerned only localization of the numeric value and the humidity calibration value edit dialog is also using just relative humidity.
> Issue #581 fix

- station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift
This issue is introduced with the implementation of #583
> Fix: Configure initial chart data before showing the chart screen

- Packages/RuuviService/Sources/RuuviServiceAuth/RuuviServiceAuthImpl.swift
This clears all cloud, claimed, and local unclaimed sensors.
> Fix: Clear sensors record from local database when user signs out #675

- station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift
This fix allows virtual sensors retain their values if other type of sensors are changed/deleted or if the user log out
> Fix: Keep observing virtual sensors when cloud or local sensors removed/updated #680

- station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsPresenter.swift
- station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/TagChartsScrollViewController.swift
After a successful or failed operation, the message is shown and a static 2 seconds delay added in between message showing and buttons showing back to give users a noticeable period to read/view the operation message.
The completion handler is not absolutely necessary in this scenario. Hence, it's not utilized as that was causing the conflict with syncRecords method above which raised issue #657
> fix: Set 2 seconds delay before showing the buttons

- Packages/RuuviService/Sources/RuuviServiceCloudSync/RuuviServiceCloudSyncImpl.swift
- station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartModuleInput.swift
- station/Classes/Presentation/Modules/Dashboard/Chart/Presenter/TagChartPresenter.swift
- station/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsInteractor.swift
Do not remove local sensors when sync from cloud. Only remove locally stored sensors which are deleted from cloud.
Remove sensor settings check before showing chart. That check was preventing charts being shown for the local sensors without settings property.
> fix: Remove sensor settings check when presenting chart #694

- station/Classes/Presentation/Modules/TagSettings/Presenter/TagSettingsPresenter.swift
Tags are now removable when the tag is not in Bluetooth range and in connecting state.
> fix: Make tag removable in connecting state #599 #403

- station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsPresenter.swift
The issue with showing the wrong error message is rectified.
> fix: Show timeout error after failed to sync #657 #643

- station/Classes/Application/Info/Impl/InfoProviderImpl.swift
- station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift
- station/Classes/Presentation/Presenters/MailComposer/MessageUI/MailComposerPresenterMessageUI.swift
- station/Resources/Plists/Info.plist
HTML markups are replaced with regular line breaks
Open default app set by user if the default mail app is not configured
> fix: Support default mail app #603

- station/Classes/Presentation/Modules/Dashboard/Cards/Presenter/CardsPresenter.swift
Tags with fw <= 2.5.9 do not show the popup.
> feature: Hide connection popup for tags with old FW #492

- station/Classes/Presentation/Modules/TagSettings/Submodules/DFU/View/DFUViewModel.swift
The original issue regarding tags not showing connectable after firmware update was not reproducible . However, a glitch was found related to that and issue #594
> fix: Store updated firmware version to local db #679

- Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/Presenter/DiscoverPresenter.swift
- Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/View/DiscoverViewInput.swift
- Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/View/Table/DiscoverTableViewController.swift
Breaking Changes!
This commit contains changes to showing sensors on the discover page which may potentially break the working feature. Needs careful testing.
> fix: Hide added sensors from discover screen #738

- station/Classes/Presentation/Modules/Dashboard/Charts/Presenter/TagChartsPresenter.swift
- station/Classes/Presentation/Modules/Dashboard/Charts/View/Scroll/TagChartsScrollViewController.swift
- station/Classes/Presentation/Modules/Dashboard/Charts/View/TagChartsViewInput.swift
- station/Classes/Presentation/Modules/Dashboard/Charts/View/TagChartsViewModel.swift
- station/Classes/Presentation/Modules/Dashboard/Charts/View/TagChartsViewOutput.swift
- station/Resources/Strings/de.lproj/Localizable.strings
- station/Resources/Strings/en.lproj/Localizable.strings
- station/Resources/Strings/fi.lproj/Localizable.strings
- station/Resources/Strings/fr.lproj/Localizable.strings
- station/Resources/Strings/ru.lproj/Localizable.strings
- station/Resources/Strings/sv.lproj/Localizable.strings
- Show confirmation alert when user tries to cancel an ongoing gatt sync.
- Show sync and clear button only for connectable tags.
> fix: Improve gatt sync experience #1027

- Packages/RuuviContext/target.yml
- Packages/RuuviOntology/target.yml
- Packages/RuuviPersistence/target.yml
- Packages/RuuviReactor/target.yml
- project_frameworks.yml
Makes all frameworks, except depending on GRDB, mergable. 
@see https://developer.apple.com/documentation/xcode/configuring-your-project-to-use-mergeable-libraries#Manually-configure-merging. 
@see: https://github.com/groue/GRDB.swift/issues/642
> Make mergable frameworks to improve launch time

- README.md
> Update README with xcodegen instructions

- scripts/install/install_firebase.sh
Firebase CLI 13 needs new node, it's a blocker
> Release 2.5.2 with Firebase CLI 12.9

- Packages/RuuviDFU/Sources/RuuviDFU/RuuviDFUError.swift
- Packages/RuuviDFU/Sources/RuuviDFUImpl/DfuFlasher.swift
- Packages/RuuviDFU/target.yml
Motivation: for single used string for the invalid arg case its not necessary to link against RuuviLocalization
> Remove dependency on RuuviLocalization in RuuviDFU

- Apps/RuuviStation/NotificationService/Sources/NotificationService.swift
- Apps/RuuviStation/NotificationService/target.yml
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/View/UI/TagChartsViewController.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/OffsetCorrection/View/Apple/OffsetCorrectionAppleViewController.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/View/UI/TagSettingsViewController.swift
- Apps/RuuviStation/Sources/Extensions/HumidityUnit+Localization.swift
- Apps/RuuviStation/Sources/Extensions/Structs/ExportHeadersProvider.swift
- Apps/RuuviStation/Sources/Station.entitlements
- Common/RuuviLocalization/Templates/strings-swift5.stencil
- Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift
Implements localization for notifications except ovement and offline
> Release 2.5.2 with Notification Service fix

- Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalIDs.swift
- Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalIDsUserDefaults.swift
- Packages/RuuviService/Sources/RuuviServiceAuth/RuuviServiceAuthImpl.swift
- Packages/RuuviService/Sources/RuuviServiceOwnership/RuuviServiceOwnershipImpl.swift
Its not private data, it is connected to this device [by uuid] only. Motivation: during sign out heartbeat received may fail to find macId
> Dont remove localIds when signing out

- Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Properties/RuuviTagPropertiesDaemonBTKit.swift
* Listen to UUID updates for given MAC E.g. the Ruuvi Tag could change its UUID because of update with nRF tools
* use observer instead of weka self
> Listen to UUID updates for given MAC (#1841)

- Apps/RuuviStation/Sources/Classes/Application/AppAssembly.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Cards/Router/CardsRouter.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/Router/DashboardRouter.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Router/TagSettingsRouter.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/DFU/Presenter/DFUModuleInput.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/DFU/Presenter/DFUPresenter.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/DFU/View/DFUViewModel.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/DFU/View/SwiftUI/DFUUIView.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/Owner/Router/OwnerRouter.swift
- Modules/RuuviDiscover/Sources/RuuviDiscover/RuuviDiscoverFactory.swift
- Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/Presenter/DiscoverPresenter.swift
- Modules/RuuviDiscover/target.yml
- Modules/RuuviFirmware/Sources/RuuviFirmware/FirmwareInteractor.swift
- Modules/RuuviFirmware/Sources/RuuviFirmware/FirmwarePresenter.swift
- Modules/RuuviFirmware/Sources/RuuviFirmware/RuuviFirmwareBuilder.swift
- Modules/RuuviFirmware/Sources/RuuviFirmware/SwiftUI/FirmwareView.swift
- Modules/RuuviFirmware/Sources/RuuviFirmware/SwiftUI/FirmwareViewModel.swift
- Modules/RuuviFirmware/target.yml
1. Idle Timer and Properties Daemon for Firmware Upgrade
Implements dont lock screen feature during firmware upgrade and fixes missing charts icon with properties daemon restart
2. Ensure you cant dismiss DFU module during upgrade
And present it modally, not pushing in navigation
> DFU improvements

- Apps/RuuviStation/Sources/Classes/Application/AppAssembly.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Cards/Router/CardsRouter.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/Router/DashboardRouter.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Router/TagSettingsRouter.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/DFU/Presenter/DFUModuleInput.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/DFU/Presenter/DFUPresenter.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/DFU/View/DFUViewModel.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/DFU/View/SwiftUI/DFUUIView.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/Owner/Router/OwnerRouter.swift
- Modules/RuuviDiscover/Sources/RuuviDiscover/RuuviDiscoverFactory.swift
- Modules/RuuviDiscover/Sources/RuuviDiscover/VMP/Presenter/DiscoverPresenter.swift
- Modules/RuuviDiscover/target.yml
- Modules/RuuviFirmware/Sources/RuuviFirmware/FirmwareInteractor.swift
- Modules/RuuviFirmware/Sources/RuuviFirmware/FirmwarePresenter.swift
- Modules/RuuviFirmware/Sources/RuuviFirmware/RuuviFirmwareBuilder.swift
- Modules/RuuviFirmware/Sources/RuuviFirmware/SwiftUI/FirmwareView.swift
- Modules/RuuviFirmware/Sources/RuuviFirmware/SwiftUI/FirmwareViewModel.swift
- Modules/RuuviFirmware/target.yml
* Idle Timer and Properties Daemon for Firmware Upgrade Implements dont lock screen feature during firmware upgrade and fixes missing charts icon with properties daemon restart
* Ensure you cant dismiss DFU module during upgrade And present it modally, not pushing
> DFU improvements (#1856)

- Apps/RuuviStation/Sources/Classes/Analytics/RuuviAnalyticsImpl.swift
- Apps/RuuviStation/Sources/Classes/Application/AppAssembly.swift
- Apps/RuuviStation/Sources/Classes/Application/AppDelegate.swift
- Apps/RuuviStation/target.yml
- Packages/RuuviAnalytics/target.yml
- Packages/RuuviPersistence/Sources/RuuviPersistenceSQLite/RuuviPersistenceSQLite.swift
Crashlytics were disabled on linking step - fixed. 
Removed report to crashlytics as not used. 
Moved analytics to main target to avoid duplicate library embedding.
> Move analytics to main target and re-enable Crashlytics

- .github/workflows/firebase.yml
- .github/workflows/testflight.yml
- Apps/RuuviStation/target.yml
- scripts/build/upload_dsyms.sh
> Upload dSYM using recommended way (#1889)

- Apps/RuuviStation/NotificationService/Sources/NotificationService.swift
- Apps/RuuviStation/Sources/Classes/Application/AppDelegate.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/Presenter/DashboardPresenter.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/View/DashboardViewOutput.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/View/UI/RUAlertDetailsCellChildView/RUAlertDetailsCellChildView.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/View/UI/TagSettingsAlertConfigCell.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/View/UI/TagSettingsFooterCell.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/View/UI/TagSettingsViewController.swift
- Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalSettings.swift
- Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift
- Packages/RuuviNotification/Sources/RuuviNotificationLocal/RuuviNotificationLocalImpl.swift
#1665 #1867 #1871 #1872 #1873 #1874
> Bug fixes and enhancements 

- Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/Removal/Presenter/SensorRemovalPresenter.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/Removal/View/SensorRemovalViewInput.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/Removal/View/UI/SensorRemovalViewController.swift
- Packages/RuuviOntology/Sources/RuuviOntology/Sensor/RuuviTag/RuuviTagSensor.swift
Previousely shared was determined by just `shared: !ruuviTag.isOwner`. This is obviousely incorrect, so I added ownership enum. Fixes #1913
> Fix removal description of not shared sensor

- Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/View/UI/TagChartsViewController.swift
Because calc depends on lowestVisibleX, and it depends on viewport, we have to wait until it recalculates after assigning data. Fixes #1758
> Dirty working fix for min/max/avg calc

- Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Defaults/Presenter/DefaultsPresenter.swift
- Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Heartbeat/RuuviTagHeartbeatDaemonBTKit.swift
- Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalSettings.swift
- Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift
- Packages/RuuviNotification/Sources/RuuviNotificationLocal/RuuviNotificationLocalImpl.swift
- Packages/RuuviService/Sources/RuuviServiceAlert/AlertPersistence/UserDefaults/AlertPersistenceUserDefaults.swift
- Instead of class cache, last triggered alert details are now stored in user defaults and offset is calculated from there. 
- Move save heartbeats foreground interval to default instead of hardcoding.
- Remove hardcoding sensor struct from uuid/macid and getting appropriate RuuviTag from RuuviStorage.
> fix: Limit alert notifications not respecting the settings #1879

- Apps/RuuviStation/target.yml
Motivation: make FLEX and Defaults visible in Firebase builds
> Use OTHER_SWIFT_FLAGS instead of GCC preprocessor definitions

- Apps/RuuviStation/target.yml
fixes:
warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'ALPHA=1')
> Fix OTHER_SWIFT_FLAG

- Apps/RuuviStation/Sources/Classes/Presentation/Modules/Share/View/ViewController/ShareViewController.swift
After moving to RuuviAsset it is not available from Storyboard
> Bring back cross icon on unshare

- Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/View/UI/TagChartsViewController.swift
Handle case of both upper and lower alert value being less than min visible Y value.
> fix: Show alert limits in graphs

- Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/Assembly/TagChartsModuleFactory.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Charts/Interactor/TagChartsViewInteractor.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/Assembly/DashboardModuleFactory.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/Presenter/DashboardPresenter.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Defaults/Presenter/DefaultsPresenter.swift
- Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/Models/Response/RuuviCloudApiUserResponse.swift
- Packages/RuuviCloud/Sources/RuuviCloudPure/RuuviCloudPure.swift
- Packages/RuuviContext/Sources/RuuviContextSQLite/SQLiteContextGRDB.swift
- Packages/RuuviDaemon/Sources/RuuviDaemonRuuviTag/Properties/RuuviTagPropertiesDaemonBTKit.swift
- Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalSettings.swift
- Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift
- Packages/RuuviNotification/Sources/RuuviNotificationLocal/RuuviNotificationLocalImpl.swift
- Packages/RuuviOntology/Sources/RuuviOntology/Mappers/RuuviTag+RuuviTagSensor.swift
- Packages/RuuviOntology/Sources/RuuviOntology/Sensor/CloudSensor.swift
- Packages/RuuviOntology/Sources/RuuviOntology/Sensor/CloudSensorDense.swift
- Packages/RuuviOntology/Sources/RuuviOntology/Sensor/RuuviTag/RuuviTagSensor.swift
- Packages/RuuviOntology/Sources/RuuviOntology/Sensor/Sensor.swift
- Packages/RuuviOntology/Sources/RuuviOntologySQLite/RuuviTagSQLite.swift
- Packages/RuuviPersistence/Sources/RuuviPersistenceSQLite/RuuviPersistenceSQLite.swift
- Packages/RuuviService/Sources/RuuviService/RuuviServiceCloudSync.swift
- Packages/RuuviService/Sources/RuuviServiceCloudSync/RuuviServiceCloudSyncImpl.swift
- Default behaviour is do history sync when user opens history page.
- Added two extra flag for enabling history sync on sign in flow, or after dashboard is visible.
- The flags are mutually exclusive but better to turn the other ones disabled and keep the intended one enabled.
> task: [Experiment] Offload history sync from sign in flow #2067

- Apps/RuuviStation/Sources/Classes/Application/AppGroupConstants.swift
- Apps/RuuviStation/Sources/Classes/Application/AppState/Impl/AppStateServiceImpl.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/Presenter/DashboardPresenter.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/Settings/Submodules/Defaults/Presenter/DefaultsPresenter.swift
- Apps/RuuviStation/Widgets/Sources/Helper/Constants.swift
- Apps/RuuviStation/Widgets/Sources/Helper/WidgetRefresher.swift
- Apps/RuuviStation/Widgets/Sources/Model/WidgetEntry.swift
- Apps/RuuviStation/Widgets/Sources/Provider/WidgetProvider.swift
- Apps/RuuviStation/Widgets/Sources/View Model/WidgetViewModel.swift
- Apps/RuuviStation/Widgets/Sources/View/SimpleWidgetView.swift
- Packages/RuuviLocal/Sources/RuuviLocal/RuuviLocalSettings.swift
- Packages/RuuviLocal/Sources/RuuviLocalUserDefaults/RuuviLocalSettingsUserDefaults.swift
- Default refresh interval is 1h.
- Can be modified from 'Defaults' flag from dev build for testing purpose. 
- Manual refresh can be done by reload button which is present on iOS 17 and above. Note that refreshing manual only updates the widget being refreshed, not all if users have more than one widget.
- Moving the app to background always refresh all widgets.
> fix: Use fixed refresh interval for widgets #1545

- Apps/RuuviStation/Sources/Classes/Presentation/Modules/SignIn/Assembly/SignInModuleFactory.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/SignIn/Presenter/SignInPresenter.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/SignIn/View/SignInViewInput.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/SignIn/View/SignInViewOutput.swift
- Apps/RuuviStation/Sources/Classes/Presentation/Modules/SignIn/View/UI/SignInViewController.swift
- Apps/RuuviStation/Sources/Extensions/Errors/RuuviCloudApiError+LocalizedError.swift
- Packages/RuuviCloud/Sources/RuuviCloud/RuuviCloudApiError.swift
- Packages/RuuviCloud/Sources/RuuviCloudApi/URLSession/RuuviCloudApiURLSession.swift
- Packages/RuuviCloud/Sources/RuuviCloudPure/RuuviCloudPure.swift
- Packages/RuuviService/Sources/RuuviServiceCloudSync/RuuviServiceCloudSyncImpl.swift
- Retry once in case of error in sensor dense endpoint from sign in flow.
- For next error show a dialog and clear previous session on OK tap so that user can start again.
> fix: Retry for failed sign in attempt #2094

- Packages/RuuviNotifier/Sources/RuuviNotifierImpl/RuuviNotifierImpl+Process.swift
- Packages/RuuviService/Sources/RuuviServiceCloudSync/RuuviServiceCloudSyncImpl.swift
Fixes the issue where alert bell keeps blinking if there are new data points available for offline alerts
> fix: Alert bell blinks even if data is new #2140

- Apps/RuuviStation/Sources/Classes/Application/AppState/Impl/AppStateServiceImpl.swift
- Packages/RuuviDaemon/Sources/RuuviDaemon/RuuviDaemonCloudSync.swift
- Packages/RuuviDaemon/Sources/RuuviDaemonCloudSync/RuuviDaemonCloudSyncWorker.swift
This prevents cloud sync daemon to wake up when things like background scanning may wake up app for processing background operations. #1545
> fix: Move cloud sync daemon start call to applicationDidBecomeActive
